### PR TITLE
[FLOC-4395] Update Flocker to use pyrsistent with PClass.set optimizations.

### PR DESCRIPTION
**Pull request by sarum90**
I just added an optimization to pyrsistent that increases the chance of getting the exact same object for equivalent PClasses.  Preliminary tests in flocker indicate that this greatly helps our comparisons when we are looking up PClasses in our lru caches.

### CODE REVIEW

**Comment by sarum90** [comment]
https://github.com/ClusterHQ/pyrsistent/commit/f881840273db5292c64289d9bccab162ad41dfec is the commit we'll be pinned to after this.

**Comment by wallrj** [comment]
LGTM. 

It'd be nice if we also incremented a version number, but I remember now that that ball's in my court  (#7) :frowning:

**Comment by sarum90** [comment]
I think that might actually be referring to https://github.com/ClusterHQ/pyrsistent/pull/7 but #7 seemed topical as well.

**Comment by sarum90** [comment]
Thanks, merging.

**Pull request merged**
