### PR TITLE
[FLOC-2019] Switch Vagrant acceptance test runner to CentOS 7

### PR DESCRIPTION
**Pull request by exarkun**
Fixes https://clusterhq.atlassian.net/browse/FLOC-2019

The tutorial box is already CentOS 7.  Directory name fix just makes the acceptance test runner aware of this.

### CODE REVIEW

**Comment by itamarst** [comment]
`acceptance/vagrant/fedora-20/zfs` is red because there's no longer a fedora-20... but there's no centos one up. Is there a branch for that?

**Comment by exarkun** [comment]
I think there's a circular dependency between the necessary Flocker changes and the necessary buildbot changes.  I don't see how to make progress without breaking something temporarily.  There's a buildbot PR that replaces `acceptance/vagrant/fedora-20/zfs` with `acceptance/vagrant/centos-7/zfs` (I think).

**Comment by itamarst** [comment]
OK.

**Comment by exarkun** [comment]
https://github.com/ClusterHQ/build.clusterhq.com/pull/96

**Pull request merged**
