### PR TITLE
Release/flocker 0.4.0pre1

### PR DESCRIPTION
**Pull request by adamtheturtle**
This is submitted for the "Post-Release Review Process" http://doc-dev.clusterhq.com/gettinginvolved/infrastructure/release-process.html#post-release-review-process

Fixes: https://clusterhq.atlassian.net/browse/FLOC-1583

### CODE REVIEW

**Comment by wallrj** [comment]
Thanks @adamtheturtle 

I guess this looks ok.

 * You've explained that the acceptance tests builder is now failing in master, but I can see that the acceptance tests *have* passed for this release in http://build.clusterhq.com/boxes-flocker?branch=release/flocker-0.4.0pre1&num_builds=10
 * The devel documentation seems to redirect correctly
 * The devel documentation seems to contain the new What's New line about Centos7 instructions and the link works: https://docs.staging.clusterhq.com/en/0.4.0pre1/indepth/installation.html#centos-7-install

Consider adding a line about Centos7 instructions to the NEWS file or create an issue to block the next pre-release.

Then proceed.

**Comment by adamtheturtle** [comment]
> You've explained that the acceptance tests builder is now failing in master, but I can see that the acceptance tests *have* passed for this release in http://build.clusterhq.com/boxes-flocker?branch=release/flocker-0.4.0pre1&num_builds=10

I've changed my mind. The release will just be blocked again by this in a few minutes when the tag has to be built so this should wait until https://clusterhq.atlassian.net/browse/FLOC-1604 is resolved.

> Consider adding a line about Centos7 instructions to the NEWS file

Done

**Comment by wallrj** [comment]
Thanks @adamtheturtle:

Here are my notes so far with some TODO items, which we can discuss tomorrow:

```
Notes:

* Supported builders are all now green: http://build.clusterhq.com/boxes-flocker?branch=0.4.0pre1


Points:

1. Documentation
   1. Redirects work
   2. Broken links are not actually broken
   3. TODO: Suggest prioritising fixing the link checker builder as part of post release improvements.

2. flocker-deploy installation
   1. Fedora20
      1. Instaled successfully
         1. `docker run --tty --interactive --volume $PWD:/flocker fedora:20 /bin/bash`
         2. `sudo yum install @buildsys-build python python-devel python-virtualenv`
         3. `sh linux-install.sh`
      2. TODO: Why isn't automated testing of `linux-install.sh` higher priority? It seems simple enough to test using Docker containers.

   2. Ubuntu 14.04

      1. Installed successfully
         1. `docker run --tty --interactive --volume $PWD:/flocker ubuntu:14.04 /bin/bash`
         2. `sudo apt-get install gcc python2.7 python-virtualenv python2.7-dev`
         3. `sh linux-install.sh`

   3. MacOSX
      1. Manually installed on Mac Mini
      2. Automated test also worked: http://build.clusterhq.com/builders/flocker%2Fhomebrew%2Ftest/builds/82
      3. TODO: Ask about automatically triggering a test of the official homebrew recipe

3. flocker-node installation
   1. Fedora20
      1. Vagrant: http://build.clusterhq.com/builders/flocker-vagrant-tutorial-box/builds/1946/steps/build-base-box/logs/stdio
         1. Machine built
         2. RPM packages installed correctly from build master repo
         3. TODO: Ideally check that package can be installed from official repo rather than build master repo.

      2. DigitalOcean: http://build.clusterhq.com/builders/flocker%2Facceptance%2Fdigitalocean%2Ffedora-20/builds/591/steps/trial/logs/stdio
         1. Broken?
         2. Failed at kernel upgrade step
         3. "Droplet is currently on. Please power it off to run this event."
         4. TODO file issue to improve DO acceptance test runner.
         5. TODO: Run those installation instructions manually

      3. AWS:
         1. Missing builder
         2. TODO: Run manually
         3. TODO: File issue to add a F20 AWS builder

      4. Rackspace: http://build.clusterhq.com/builders/flocker%2Facceptance%2Frackspace%2Ffedora-20/builds/488/steps/trial/logs/stdio
         1. Machine built
         2. RPM packages installed from build master repo
            1. `yum install --enablerepo=clusterhq-build -y clusterhq-flocker-node-0.4.0-0.pre.1`

      5. Repoquery
         1. TODO: File an issue to suggest a Repoquery step which ensures that the tagged package is available from our official repo.

   2. Centos7
      1. Vagrant:
         1. TODO: Run tests manually
         2. TODO: Propose that Centos7 demo box is high priority and add comment to issue.

      2. AWS: http://build.clusterhq.com/builders/flocker%2Facceptance%2Faws%2Fcentos-7/builds/539
         1. Machine built
         2. Packages installed
         3. Acceptance test errors
         4. TODO: Run tests manually

      3. Rackspace: http://build.clusterhq.com/builders/flocker%2Facceptance%2Frackspace%2Fcentos-7/builds/521
         1. Machine build failed
         2. "403 Forbidden Quota exceeded for ram: Requested 8192, but already used 249600 of 256000 ram"
         3. TODO: run tests manually

      4. DigitalOcean:
         1. TODO: File an issue for automatic Centos7 acceptance tests on Digital Ocean
         2. TODO: Run manually
```

**Comment by adamtheturtle** [comment]
>       3. TODO: Ask about automatically triggering a test of the official homebrew recipe

@jongiddy has been working on this and is close AFAIK. This should make the process "Download the tested recipe from Buildbot. Upload that recipe to GitHub. No review necessary".

**Comment by adamtheturtle** [comment]
>   3. TODO: Suggest prioritising fixing the link checker builder as part of post release improvements.

Makes sense, will do.

**Comment by adamtheturtle** [comment]
>          3. TODO: File issue to add a F20 AWS builder

We are dropping F20 so probably not worthwhile.

**Comment by adamtheturtle** [comment]
> "403 Forbidden Quota exceeded for ram: Requested 8192, but already used 249600 of 256000 ram"

https://clusterhq.atlassian.net/browse/FLOC-1619

**Comment by adamtheturtle** [comment]
>          2. TODO: Propose that Centos7 demo box is high priority and add comment to issue.

Why would it increase in priority?

**Comment by adamtheturtle** [comment]
>         1. TODO: File an issue to suggest a Repoquery step which ensures that the tagged package is available from our official repo.

Is https://clusterhq.atlassian.net/browse/FLOC-1620 sufficient?

**Comment by wallrj** [comment]
Thanks @adamtheturtle:

This morning I've:

 * Re-tested all the client installation instructions, as follows:

```
flocker-deploy installation
   1. Fedora20
      1. Getting Started: Works
      2. In Depth: Works
      3. Mongo Client: Works 2.4.6

   2. Ubuntu 14.04
      1. Getting Started: Works
      2. In Depth: Works
      3. Mongo Client: Works

   3. MacOSX
      1. In Depth: Works
      2. Getting Started: Works
      3. Mongo Client: Works
```

 * Manually tested flocker-node installation on a Centos7 box 

```
Dependencies Resolved

======================================================================================================================================================
 Package                                  Arch                   Version                                      Repository                         Size
======================================================================================================================================================
Installing:
 clusterhq-flocker-node                   noarch                 0.4.0-0.pre.1                                clusterhq-testing                 4.6 k
Installing for dependencies:
 clusterhq-python-flocker                 x86_64                 0.4.0-0.pre.1                                clusterhq-testing                  12 M
 dkms                                     noarch                 2.2.0.3-30.git.7c3e7c5.el7                   epel                               77 k
 docker                                   x86_64                 1.4.1-37.chq3.el7.centos                     clusterhq                         7.1 M
 libnvpair1                               x86_64                 0.6.3-1.3.el7.centos                         zfs                                28 k
 libuutil1                                x86_64                 0.6.3-1.3.el7.centos                         zfs                                34 k
 libzfs2                                  x86_64                 0.6.3-1.3.el7.centos                         zfs                               113 k
 libzpool2                                x86_64                 0.6.3-1.3.el7.centos                         zfs                               392 k
 spl                                      x86_64                 0.6.3-1.3.el7.centos                         zfs                                24 k
 spl-dkms                                 noarch                 0.6.3-1.3.el7.centos                         zfs                               451 k
 zfs                                      x86_64                 0.6.3-1.3.el7.centos                         zfs                               292 k
 zfs-dkms                                 noarch                 0.6.3-1.3.el7.centos                         zfs                               1.7 M

Transaction Summary
======================================================================================================================================================
Install  1 Package (+11 Dependent packages)

Total download size: 22 M
Installed size: 92 M

```

 * Run through the ELK tutorial on Centos7 nodes

 * Ran the getting started guide using the 0.4.0pre1 branch of the external repo.

```
Getting started

      1. Fedora Client: Works

         git clone \
         https://github.com/clusterhq/vagrant-flocker && \
         cd vagrant-flocker && \
         git checkout 0.4.0pre1-FLOC-1583 && \
         vagrant up && \
         [ -e "${SSH_AUTH_SOCK}" ] || eval $(ssh-agent) && \
         ssh-add ~/.vagrant.d/insecure_private_key
```

We'd originally said that we weren't going to worry about the known broken Fedora20 AWS instructions, 
* https://clusterhq.atlassian.net/browse/FLOC-1455

...but there's been some discussion in Bristol, and that may turn out to be a blocker.

**Pull request merged**
