### PR TITLE
[FLOC-4348] Deprecate and remove the labs installer documentation

### PR DESCRIPTION
**Pull request by wallrj**
Fixes: https://clusterhq.atlassian.net/browse/FLOC-4348

Rendered docs:
 * http://clusterhq-staging-docs.s3-website-us-east-1.amazonaws.com/deprecate-labs-installer-FLOC-4348/

See also:
* https://github.com/ClusterHQ/unofficial-flocker-tools/pull/72

### CODE REVIEW

**Comment by wallnerryan** [comment]
Looks good, is there a way to see the docs how they would look with these changes, e.g. staging somewhere?

few build failures, once your confident these are not related and I can view staging version i can give go ahead

**Comment by wallrj** [comment]
Thanks @wallnerryan 
I forgot to paste the link to the rendered docs.
You go to the "jenkins-run_sphinx" build details (above) > click "Console Output" > scoll almost to eh bottom where there'll be a link to the rendered docs:
 * http://clusterhq-staging-docs.s3-website-us-east-1.amazonaws.com/deprecate-labs-installer-FLOC-4348/

**Comment by wallrj** [comment]
Ah damn, those test failures are caused by a change I made in #2872 this morning and was too impatient to wait for new builds before merging.
Lesson learned...again.
I'll fix those before merging this branch.

**Comment by wallnerryan** [comment]
now that "install manually" is the only option, I wonder if its worth adding a pointer to "use ansible" and point to https://github.com/ClusterHQ/ansible-role-flocker. Or possibly adding the docs for it. Probably a seperate issue though.

**Comment by wallnerryan** [comment]
overall looks good, but we do still have pointers to blogs in our docs that use the UFT installer such as http://clusterhq-staging-docs.s3-website-us-east-1.amazonaws.com/deprecate-labs-installer-FLOC-4348/kubernetes-integration/

i think there are two options, add some type of warning to the uft script, or I can try and do a bulk warning on blog posts. The second option may be more clear to users who dont pay attention to output.

otherwise LGTM, so merge when you are happy, but would like feedback on the above.

**Comment by wallrj** [comment]
> now that "install manually" is the only option, I wonder if its worth adding a pointer to "use ansible" and point to https://github.com/ClusterHQ/ansible-role-flocker. Or possibly adding the docs for it. Probably a seperate issue though.

I agree. I'd like to add that installation method to the list, but haven't test it myself. 
Let's aim to include that in the next release.

**Comment by wallrj** [comment]
> i think there are two options, add some type of warning to the uft script, or I can try and do a bulk warning on blog posts. The second option may be more clear to users who dont pay attention to output.

I added a deprecation warning message to all the uft-* comands.
See https://github.com/ClusterHQ/unofficial-flocker-tools/pull/72

**Pull request merged**
