### PR TITLE
[FLOC-2254] Release Flocker 0.9.0

### PR DESCRIPTION
**Pull request by adamtheturtle**
All failing tests have, I think, been deemed acceptable.

Please follow the "Pre-tag Review Process" at:

http://doc-dev.clusterhq.com/gettinginvolved/infrastructure/release-process.html#pre-tag-review-process

### CODE REVIEW

**Comment by myechuri** [comment]
- Test failures from below 3 tests are because of Rackspace OverLimit, which masks test results: we do not know if the tests would have passed if we didn't hit rate limits.
functional/rackspace/centos-7/storage-driver
client/rackspace/ubuntu-14.04
client/rackspace/ubuntu-15.04

- Maybe we should wait for acceptance/vagrant/centos-7/zfs and installed-package/vagrant/centos-7 results before tagging?

- Not clear from http://doc-dev.clusterhq.com/gettinginvolved/infrastructure/release-process.html#pre-tag-review-process if "The release notes at docs/releasenotes/index.rst should be up to date." is a mandatory update or not.

Thanks, @adamtheturtle !

**Comment by myechuri** [comment]
@adamtheturtle : can you please continue once acceptance/vagrant/centos-7/zfs and installed-package/vagrant/centos-7 results are out? Thanks!

**Comment by adamtheturtle** [comment]
Thanks for the review @myechuri . Apologies I should have linked to the following Zulip topic: https://zulip.com/#narrow/stream/engineering/subject/0.2E9. This says that nothing "except known bugs in the release process should block it" in terms of blocking issues.

Therefore:

> Maybe we should wait for acceptance/vagrant/centos-7/zfs and installed-package/vagrant/centos-7 results before tagging?

I don't think so because we'd continue anyways.

> Not clear from http://doc-dev.clusterhq.com/gettinginvolved/infrastructure/release-process.html#pre-tag-review-process if "The release notes at docs/releasenotes/index.rst should be up to date." is a mandatory update or not.

It is - but I think that the notes are up to date.

Based on the above, can I continue now?

**Comment by adamtheturtle** [comment]
(permission given on Zulip)

**Pull request merged**
