### PR TITLE
[FLOC-3894] Lower the clone timeout and raise the checkout retry count.

### PR DESCRIPTION
**Pull request by exarkun**
Fixes https://clusterhq.atlassian.net/browse/FLOC-3894

### CODE REVIEW

**Comment by exarkun** [comment]
Some bugs fixed in the GitSCM Jenkins plugin, in 2.4.0, might also be relevant to this change.  So it might be productive to look into upgrading our deployment to use that version of the plugin as well.

**Comment by james-w** [comment]
:+1: Looks perfectly reasonable, thanks for improving it. Down with all failure conditions!

@jml mentor review please

**Comment by james-w** [comment]
btw you got a red from jenkins, but all the actual tests passed, I'm looking
in to what is causing that today.

**Comment by jml** [comment]
:+1:

**Pull request merged**
