### PR TITLE
[FLOC-3129] "Using" section for FPD docs

### PR DESCRIPTION
**Pull request by robhaswell**
https://clusterhq.atlassian.net/browse/FLOC-3129

This PR adds instructions on using the Flocker plugin for Docker, and duplicates the known limitations into this section by way of an include.

One current problem is that the remote API is undocumented at Docker. This will be fixed soon, and is stable. It's debatable whether we should even include this documentation. My position is that it does no harm.

Another important change here is to add an `_include` directory into `docs` and ignore it (similar to `_build`).

[Review on Reviewable](https://reviewable.io/reviews/clusterhq/flocker/2000)

### CODE REVIEW

**Comment by tomprince** [comment]
@robhaswell  Since we don't usually have PRs against feature branches, can you add some comments about how this is supposed to be reviewed, and how that relates to the eventual review of the branch this is going to be merged to?

**Comment by robhaswell** [comment]
Sure, @davidoliverSP2 is going to review this as an addition to his branch. Then the documentation ca be reviewed as a whole.

**Comment by robhaswell** [comment]
@davidoliverSP2 I think that the known limitations are important enough that they should be in both places. I also wonder if they should be callouts.

**Comment by davidoliverSP2** [comment]
thanks @robhaswell  - the way it was structured it was causing build breaks. I'll find a way to restructure it.

**Comment by robhaswell** [comment]
Weird... It built locally.

**Comment by robhaswell** [comment]
@davidoliverSP2 I found a way.

**Comment by davidoliverSP2** [comment]
as 2760 has now been merged, these changes have been transferred into https://github.com/ClusterHQ/flocker/pull/2007, branched off master.

This PR can be closed.

**Pull request closed without merging**
