### PR TITLE
[FLOC-4328] Update plugin documentation to require unicode for `required_config`.

### PR DESCRIPTION
**Pull request by tomprince**
https://clusterhq.atlassian.net/browse/FLOC-4238

This is in preperation for #2659.

### CODE REVIEW

**Comment by sarum90** [comment]
This should definitely go in.

I think we may want to be more lenient on the other one though.

**Comment by sarum90** [comment]
Also, Thanks!

**Comment by davidoliverSP2** [comment]
Looks good to me too - thanks @tomprince

**Comment by tomprince** [comment]
Merged as part of #2666.

**Comment by wallrj** [comment]
I'm going to try merging this into `release/flocker-1.10.2`.

**Comment by sarum90** [comment]
Thanks @wallrj. Sorry for not facilitating this coordination with tom on Friday. The thought crossed my mind... and then something else came up.

**Pull request merged**
