### PR TITLE
[FLOC 2658] Move the cluster install steps to a new document

### PR DESCRIPTION
**Pull request by davidoliverSP2**
Fixes 2658

Due to this partially being completed on FLOC 2657, this PR only includes the addition of contents, and an amendment to the Next Steps text.

The final sub task of Story 2644 will move the Authentication steps into the Install section (FLOC 2716)

### CODE REVIEW

**Comment by jongiddy** [comment]
Although the changes you've made are fine, some comments on the page itself. Perhaps these comments should be addressed as follow-up issues.

**Comment by jongiddy** [comment]
The title "What to do next" is out of place with the subsequent title of "Next Step". Since this only contains the optional ZFS installation, it seems unnecessary - perhaps rename this step to "Backend Configuration Options".  This also allows you to remove "Optional" from the ZFS title.  Although it is important to emphasize that ZFS is not required, it is awkward to have the optionality as part of the title.  Also, the first sentence "If you intend to use a ZFS backend, this requires ZFS to be installed." is terrible.

How about something like:

Backend Configuration Options
========================
Some backends require additional installation and configuration. This is only required if you intend to use this backend.

ZFS Backend
-----------------

Installing ZFS on CentOS7
~~~~~~~~~~~~~~~

**Comment by jongiddy** [comment]
Related, but separate, the "ZFS Peer-to-Peer Backend Configuration" section says that "[t]he pool name must match a ZFS storage pool that you have created on all of the Flocker agent nodes" but we have not yet seen the ZFS installation and configuration section. Perhaps this section needs a a forward reference to provide more information: "See ZFS Backend Configuration".

**Comment by jongiddy** [comment]
Despite these comments, which I'm happy to leave with you for future consideration, I'm happy for this to be merged as is.

**Comment by davidoliverSP2** [comment]
Thanks @jongiddy - when the tests are complete I'll merge this.

The following issues track your suggestions for future work:
* FLOC 2724: Rename the "What to do next" section on the Post-install Config page
* FLOC 2725: Add a link to "ZFS Peer-to-Peer Backend Configuration" section

**Pull request merged**
