### PR TITLE
[FLOC 3190] Updates to the configuring authentication docs

### PR DESCRIPTION
**Pull request by davidoliverSP2**
Fixes 3190

This PR rewrites the authentication steps, following a run through between myself, @alicesowerby and @Stephenitis 

The authentication has been split into 2 documents, covering the creation and renaming of certificates, and then the API end user certificates.

[Review on Reviewable](https://reviewable.io/reviews/clusterhq/flocker/2051)

### CODE REVIEW

**Comment by sarum90** [comment]
Good stuff. Just took a glance at the current docs and this seems like a big improvement.

I've got a couple newb questions as I was going through this:
* How do you normally build the docs? `tox -e sphinx` as per https://docs.clusterhq.com/en/1.4.0/gettinginvolved/contributing.html#documentation failed for me with "spelling errors". Nothing a little hacking on our spellfile couldn't fix, but I had to do that in order to build the docs for my local viewing.
* I didn't actually go through the directions and actually set up a cluster to verify it works. I did run a lot of the flocker-ca commands to verify the output was as expected, but at a large level I'm assuming this works as described. I'm comfortable with that being the bar for the review, is that the normal bar for review?
* Really feel free to ignore my :grey_question: comments at your discretion. They were things I noticed, and thought they might deserve a second look by you, but are also fine as is.


---

Review status: 0 of 4 files reviewed at latest revision, 12 unresolved discussions, all commit checks successful.

---

<sup>**[docs/config/configuring-authentication.rst, line 28 \[r1\]](https://reviewable.io:443/reviews/clusterhq/flocker/2051#-K10FeuKGlcJOA9FuWIp)** ([raw file](https://github.com/clusterhq/flocker/blob/80e81fcbd2935235dd25dc30335a6733af7b0b96/docs/config/configuring-authentication.rst#L28)):</sup>
:grey_question: I think this is now done on a subsequent page. Not sure how or if you want to indicate that here, or if this line should just be dropped.


---

<sup>**[docs/config/configuring-authentication.rst, line 56 \[r1\]](https://reviewable.io:443/reviews/clusterhq/flocker/2051#-K106nC7tgazwRJJXPAh)** ([raw file](https://github.com/clusterhq/flocker/blob/80e81fcbd2935235dd25dc30335a6733af7b0b96/docs/config/configuring-authentication.rst#L56)):</sup>
I think `cluster.key` and `cluster.crt` are just in the current working directory after the above command is run. Copying them to `/etc/flocker/` on the control node is covered later. Presumably these are just run on the users laptop, which might not even have a `/etc/flocker` directory.


---

<sup>**[docs/config/configuring-authentication.rst, line 74 \[r1\]](https://reviewable.io:443/reviews/clusterhq/flocker/2051#-K10V2-DNQKjGA-XHl3O)** ([raw file](https://github.com/clusterhq/flocker/blob/80e81fcbd2935235dd25dc30335a6733af7b0b96/docs/config/configuring-authentication.rst#L74)):</sup>
I think this is now Step 2. Is there any fancy way to reference bullets (intellectual curiosity)?


---

<sup>**[docs/config/configuring-authentication.rst, line 80 \[r1\]](https://reviewable.io:443/reviews/clusterhq/flocker/2051#-K10EBwpbo7rZQj4UFR3)** ([raw file](https://github.com/clusterhq/flocker/blob/80e81fcbd2935235dd25dc30335a6733af7b0b96/docs/config/configuring-authentication.rst#L80)):</sup>
I think these also are just in the current working directory rather than in `/etc/flocker` - same as above.


---

<sup>**[docs/config/configuring-authentication.rst, line 113 \[r1\]](https://reviewable.io:443/reviews/clusterhq/flocker/2051#-K10VNnlplBsVk3wPxU_)** ([raw file](https://github.com/clusterhq/flocker/blob/80e81fcbd2935235dd25dc30335a6733af7b0b96/docs/config/configuring-authentication.rst#L113)):</sup>
Ditto about this now being Step 2.


---

<sup>**[docs/config/configuring-authentication.rst, line 117 \[r1\]](https://reviewable.io:443/reviews/clusterhq/flocker/2051#-K10EoVD8gRtaXbvFFEH)** ([raw file](https://github.com/clusterhq/flocker/blob/80e81fcbd2935235dd25dc30335a6733af7b0b96/docs/config/configuring-authentication.rst#L117)):</sup>
:grey_question: Same question on the trailing three spaces.


---

<sup>**[docs/config/generate-api-certificates.rst, line 9 \[r1\]](https://reviewable.io:443/reviews/clusterhq/flocker/2051#-K1-zZIBz07rGc4_AxRd)** ([raw file](https://github.com/clusterhq/flocker/blob/80e81fcbd2935235dd25dc30335a6733af7b0b96/docs/config/generate-api-certificates.rst#L9)):</sup>
This looks suspiciously like an unfinished link.


---

<sup>**[docs/config/generate-api-certificates.rst, line 15 \[r1\]](https://reviewable.io:443/reviews/clusterhq/flocker/2051#-K1-zCG1Pijz8PoZJ6Vy)** ([raw file](https://github.com/clusterhq/flocker/blob/80e81fcbd2935235dd25dc30335a6733af7b0b96/docs/config/generate-api-certificates.rst#L15)):</sup>
When I build the docs locally this looks like:
```
$ $ flocker-ca create-api-certificate <username>
```
Presumably we don't what the `$` here? Or do we need `auto` or something?


---

<sup>**[docs/config/generate-api-certificates.rst, line 25 \[r1\]](https://reviewable.io:443/reviews/clusterhq/flocker/2051#-K10-bTRav67P1DK-FwQ)** ([raw file](https://github.com/clusterhq/flocker/blob/80e81fcbd2935235dd25dc30335a6733af7b0b96/docs/config/generate-api-certificates.rst#L25)):</sup>
:grey_question: Extra spaces at the end of a line. Do they have a function? otherwise slight preference to remove.


---

<sup>**[docs/config/generate-api-certificates.rst, line 30 \[r1\]](https://reviewable.io:443/reviews/clusterhq/flocker/2051#-K100wqeEl132DSugWSN)** ([raw file](https://github.com/clusterhq/flocker/blob/80e81fcbd2935235dd25dc30335a6733af7b0b96/docs/config/generate-api-certificates.rst#L30)):</sup>
:grey_question: Looks like this is just a re-organization, but to me the second line seems redundant to the first line. Perhaps a concrete example would be better for the second line? I'll defer to you on if that's worth pursuing.


---

<sup>**[docs/config/generate-api-certificates.rst, line 36 \[r1\]](https://reviewable.io:443/reviews/clusterhq/flocker/2051#-K1009_jnMH8vJUpYi7l)** ([raw file](https://github.com/clusterhq/flocker/blob/80e81fcbd2935235dd25dc30335a6733af7b0b96/docs/config/generate-api-certificates.rst#L36)):</sup>
:grey_question: there is a double space between "an  API". Prefer single space. Although, that's not rendered so.... super optional.


---

<sup>**[docs/config/generate-api-certificates.rst, line 81 \[r1\]](https://reviewable.io:443/reviews/clusterhq/flocker/2051#-K1051hRX8H0AG4o_VOQ)** ([raw file](https://github.com/clusterhq/flocker/blob/80e81fcbd2935235dd25dc30335a6733af7b0b96/docs/config/generate-api-certificates.rst#L81)):</sup>
:grey_question:  Should `<security>` link back here as well? Seems that if someone is at `<mutual-authentication-overview>` it would be a shame if they failed to get the leap from learning that ``flocker-ca`` exists to finding this page.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/clusterhq/flocker/2051)

**Comment by tomprince** [comment]
> I didn't actually go through the directions and actually set up a cluster to verify it works. I did run a lot of the flocker-ca commands to verify the output was as expected, but at a large level I'm assuming this works as described. I'm comfortable with that being the bar for the review, is that the normal bar for review?

What I generally do, when I haven't actually tested changes like this, when I am giving an otherwise passing review, is to add verifying that the changes work as part of the conditions for merging. As a submitter, I don't always test things before submitting (typically when it is at the end of my day, so that I can take advantage of the timezone spread), but I try to make that explicit in the pull-request. Similarly, when reviewing, I'll make it explicit if I've actually tested things manually.

**Comment by adamtheturtle** [comment]
@sarum90:

> How do you normally build the docs?

The spellcheck relies on the system dictionary which is different on each platform. Just note here which new spelling errors show up for you and they can be added to the spelling wordlist. To build docs for local viewing you can change into the `docs` directory and `make html` and this bypasses the spellcheck


---

Review status: 0 of 4 files reviewed at latest revision, 10 unresolved discussions, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/clusterhq/flocker/2051)

**Comment by sarum90** [comment]
This looks great to me. I'd be fine with merging this as is. I've got a couple points that I think would improve consistency, but they don't need to block submission.

Certainly not for this pull request, but it's almost tempting to make a slightly larger copy-paste-able blob for some of the steps, for example:
```
      HOSTNAME=<hostname>
      UUID=<yourUUID>
      scp $UUID.crt root@$HOSTNAME:/etc/flocker/
      scp $UUID.key root@$HOSTNAME:/etc/flocker/
      scp cluster.crt root@$HOSTNAME:/etc/flocker/
      ssh root@$HOSTNAME chmod 0700 /etc/flocker
      ssh root@$HOSTNAME chmod 0600 /etc/flocker/node.key
```
Not sure if it's a clear win though.... so maybe I'd defer to Alice or you on if something like that would be better -- and at that point you are starting down a path of essentially writing the installer in bash samples, so maybe that's not the intended audience for this documentation anyway.


---

Reviewed 2 of 4 files at r1, 3 of 4 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

<sup>**[docs/config/configuring-authentication.rst, line 74 \[r1\]](https://reviewable.io:443/reviews/clusterhq/flocker/2051#-K10V2-DNQKjGA-XHl3O)** ([raw file](https://github.com/clusterhq/flocker/blob/80e81fcbd2935235dd25dc30335a6733af7b0b96/docs/config/configuring-authentication.rst#L74)):</sup>
:grey_question: Seems that you now call this ```the `flocker-ca initialize` step``` elsewhere, might be a nice way to guard against step increments.


---

<sup>**[docs/config/configuring-authentication.rst, line 95 \[r3\]](https://reviewable.io:443/reviews/clusterhq/flocker/2051#-K15gf-qRQRoKF2uZs0Z)** ([raw file](https://github.com/clusterhq/flocker/blob/93efea4463261f20f1710ce888378b1e5d0784f2/docs/config/configuring-authentication.rst#L95)):</sup>
These are great :smile:.


---

<sup>**[docs/config/generate-api-certificates.rst, line 25 \[r3\]](https://reviewable.io:443/reviews/clusterhq/flocker/2051#-K15kQBKy5d-6bFjIlak)** ([raw file](https://github.com/clusterhq/flocker/blob/93efea4463261f20f1710ce888378b1e5d0784f2/docs/config/generate-api-certificates.rst#L25)):</sup>
:grey_question: Probably for consistency with the other page add the ```(as created by the `flocker-ca initialize` step of :ref:`authentication`)``` here to match the other page.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/clusterhq/flocker/2051)

**Comment by davidoliverSP2** [comment]
@sarum90 Many thanks for your review - really great feedback!! The comments not addressed I'll go through with @alicesowerby as part of the acceptance criteria review on FLOC-3085 (the parent story)

**Pull request merged**
