### PR TITLE
[FLOC-4487] Remove container agent firewall manipulation and NAT routing 

### PR DESCRIPTION
**Pull request by wallrj**
Fixes: https://clusterhq.atlassian.net/browse/FLOC-4487

I've removed all traces of the NAT routing code and the manipulation of open ports for exposed ports.

I'll post benchmark results later.

But with out this, I wasn't even able to create the desired 2000 postgresql containers with exposed ports....the flocker-container-agents became too unresponsive and their AMP protocol connections timed out.

Benchmark results:

 * Using a modified version of the benchmarking package: https://github.com/ClusterHQ/flocker/compare/benchmark-with-exposed-ports
 * And this branch manually hacked into an existing 1.14.0 cluster by scping the modified _containers module to all the nodes and restarting agents.

```
$ ./benchmark/setup-cluster-containers --apps-per-node 19  --image postgres --mountpoint /var/lib/postgresql --control-node $FLOCKER_ACCEPTANCE_CONTROL_NODE --cert-directory $FLOCKER_ACCEPTANCE_API_CERTIFICATES_PATH
```

```
$ ./benchmark --samples 20 --metric wallclock --operation create-container > results-create-container-with-ports-norouting 2>logs-create-container-with-ports-norouting
```

```
{
  "client": {
    "username": "richard", 
    "platform": "Linux-4.4.0-34-generic-x86_64-with-Ubuntu-16.04-xenial", 
    "working_directory": "/home/richard/flocker/benchmark", 
    "nodename": "richardw-pet-ubuntu1604", 
    "flocker_version": "1.14.0+1.g40433b3.dirty"
  }, 
  "version": 1, 
  "scenario": {
    "type": "no-load", 
    "name": "default"
  }, 
  "control_service": {
    "flocker_version": "1.14.0", 
    "dataset_count": 1919, 
    "container_count": 1919, 
    "node_count": 100, 
    "host": "104.196.161.93"
  }, 
  "timestamp": "2016-08-23T07:40:53.348776", 
  "metric": {
    "type": "wallclock", 
    "name": "wallclock"
  }, 
  "samples": [
    {
      "value": 10.845351934432983, 
      "success": true
    }, 
    {
      "reason": "Traceback (most recent call last):\nFailure: twisted.internet.defer.FirstError: FirstError[#1, [Failure instance: Traceback (failure with no frames): <class 'twisted.internet.defer.CancelledError'>: \n]]\n", 
      "success": false
    }, 
    {
      "reason": "Traceback (most recent call last):\n  File \"/home/richard/.venvs/benchmarking/local/lib/python2.7/site-packages/treq/client.py\", line 62, in connectionLost\n    self.original.connectionLost(reason)\n  File \"/home/richard/.venvs/benchmarking/local/lib/python2.7/site-packages/treq/content.py\", line 38, in connectionLost\n    self.finished.callback(None)\n  File \"/home/richard/.venvs/benchmarking/local/lib/python2.7/site-packages/twisted/internet/defer.py\", line 393, in callback\n    self._startRunCallbacks(result)\n  File \"/home/richard/.venvs/benchmarking/local/lib/python2.7/site-packages/twisted/internet/defer.py\", line 501, in _startRunCallbacks\n    self._runCallbacks()\n--- <exception caught here> ---\n  File \"/home/richard/.venvs/benchmarking/local/lib/python2.7/site-packages/twisted/internet/defer.py\", line 588, in _runCallbacks\n    current.result = callback(current.result, *args, **kw)\n  File \"/home/richard/flocker/flocker/apiclient/_client.py\", line 624, in error\n    raise error_codes[code](body)\nflocker.apiclient._client.ContainerAlreadyExists: {\"description\": \"A specified external port is already in use.\"}\n", 
      "success": false
    }, 
    {
      "value": 10.779719829559326, 
      "success": true
    }, 
    {
      "value": 10.844377040863037, 
      "success": true
    }, 
    {
      "reason": "Traceback (most recent call last):\n  File \"/home/richard/.venvs/benchmarking/local/lib/python2.7/site-packages/treq/client.py\", line 62, in connectionLost\n    self.original.connectionLost(reason)\n  File \"/home/richard/.venvs/benchmarking/local/lib/python2.7/site-packages/treq/content.py\", line 38, in connectionLost\n    self.finished.callback(None)\n  File \"/home/richard/.venvs/benchmarking/local/lib/python2.7/site-packages/twisted/internet/defer.py\", line 393, in callback\n    self._startRunCallbacks(result)\n  File \"/home/richard/.venvs/benchmarking/local/lib/python2.7/site-packages/twisted/internet/defer.py\", line 501, in _startRunCallbacks\n    self._runCallbacks()\n--- <exception caught here> ---\n  File \"/home/richard/.venvs/benchmarking/local/lib/python2.7/site-packages/twisted/internet/defer.py\", line 588, in _runCallbacks\n    current.result = callback(current.result, *args, **kw)\n  File \"/home/richard/flocker/flocker/apiclient/_client.py\", line 624, in error\n    raise error_codes[code](body)\nflocker.apiclient._client.ContainerAlreadyExists: {\"description\": \"A specified external port is already in use.\"}\n", 
      "success": false
    }, 
    {
      "value": 10.742519855499268, 
      "success": true
    }, 
    {
      "value": 10.880398035049438, 
      "success": true
    }, 
    {
      "reason": "Traceback (most recent call last):\nFailure: twisted.internet.defer.FirstError: FirstError[#0, [Failure instance: Traceback: <class 'flocker.apiclient._client.ContainerAlreadyExists'>: {\"description\": \"A specified external port is already in use.\"}\n/home/richard/.venvs/benchmarking/local/lib/python2.7/site-packages/treq/client.py:62:connectionLost\n/home/richard/.venvs/benchmarking/local/lib/python2.7/site-packages/treq/content.py:38:connectionLost\n/home/richard/.venvs/benchmarking/local/lib/python2.7/site-packages/twisted/internet/defer.py:393:callback\n/home/richard/.venvs/benchmarking/local/lib/python2.7/site-packages/twisted/internet/defer.py:501:_startRunCallbacks\n--- <exception caught here> ---\n/home/richard/.venvs/benchmarking/local/lib/python2.7/site-packages/twisted/internet/defer.py:588:_runCallbacks\n/home/richard/flocker/flocker/apiclient/_client.py:624:error\n]]\n", 
      "success": false
    }, 
    {
      "value": 11.706778049468994, 
      "success": true
    }, 
    {
      "value": 10.86034893989563, 
      "success": true
    }, 
    {
      "value": 10.746649980545044, 
      "success": true
    }, 
    {
      "reason": "Traceback (most recent call last):\n  File \"/home/richard/.venvs/benchmarking/local/lib/python2.7/site-packages/treq/client.py\", line 62, in connectionLost\n    self.original.connectionLost(reason)\n  File \"/home/richard/.venvs/benchmarking/local/lib/python2.7/site-packages/treq/content.py\", line 38, in connectionLost\n    self.finished.callback(None)\n  File \"/home/richard/.venvs/benchmarking/local/lib/python2.7/site-packages/twisted/internet/defer.py\", line 393, in callback\n    self._startRunCallbacks(result)\n  File \"/home/richard/.venvs/benchmarking/local/lib/python2.7/site-packages/twisted/internet/defer.py\", line 501, in _startRunCallbacks\n    self._runCallbacks()\n--- <exception caught here> ---\n  File \"/home/richard/.venvs/benchmarking/local/lib/python2.7/site-packages/twisted/internet/defer.py\", line 588, in _runCallbacks\n    current.result = callback(current.result, *args, **kw)\n  File \"/home/richard/flocker/flocker/apiclient/_client.py\", line 624, in error\n    raise error_codes[code](body)\nflocker.apiclient._client.ContainerAlreadyExists: {\"description\": \"A specified external port is already in use.\"}\n", 
      "success": false
    }, 
    {
      "value": 10.95711898803711, 
      "success": true
    }, 
    {
      "value": 10.909873962402344, 
      "success": true
    }, 
    {
      "value": 10.804506063461304, 
      "success": true
    }, 
    {
      "reason": "Traceback (most recent call last):\nFailure: twisted.internet.defer.FirstError: FirstError[#0, [Failure instance: Traceback: <class 'flocker.apiclient._client.ContainerAlreadyExists'>: {\"description\": \"A specified external port is already in use.\"}\n/home/richard/.venvs/benchmarking/local/lib/python2.7/site-packages/treq/client.py:62:connectionLost\n/home/richard/.venvs/benchmarking/local/lib/python2.7/site-packages/treq/content.py:38:connectionLost\n/home/richard/.venvs/benchmarking/local/lib/python2.7/site-packages/twisted/internet/defer.py:393:callback\n/home/richard/.venvs/benchmarking/local/lib/python2.7/site-packages/twisted/internet/defer.py:501:_startRunCallbacks\n--- <exception caught here> ---\n/home/richard/.venvs/benchmarking/local/lib/python2.7/site-packages/twisted/internet/defer.py:588:_runCallbacks\n/home/richard/flocker/flocker/apiclient/_client.py:624:error\n]]\n", 
      "success": false
    }, 
    {
      "reason": "Traceback (most recent call last):\n  File \"/home/richard/.venvs/benchmarking/local/lib/python2.7/site-packages/treq/client.py\", line 62, in connectionLost\n    self.original.connectionLost(reason)\n  File \"/home/richard/.venvs/benchmarking/local/lib/python2.7/site-packages/treq/content.py\", line 38, in connectionLost\n    self.finished.callback(None)\n  File \"/home/richard/.venvs/benchmarking/local/lib/python2.7/site-packages/twisted/internet/defer.py\", line 393, in callback\n    self._startRunCallbacks(result)\n  File \"/home/richard/.venvs/benchmarking/local/lib/python2.7/site-packages/twisted/internet/defer.py\", line 501, in _startRunCallbacks\n    self._runCallbacks()\n--- <exception caught here> ---\n  File \"/home/richard/.venvs/benchmarking/local/lib/python2.7/site-packages/twisted/internet/defer.py\", line 588, in _runCallbacks\n    current.result = callback(current.result, *args, **kw)\n  File \"/home/richard/flocker/flocker/apiclient/_client.py\", line 624, in error\n    raise error_codes[code](body)\nflocker.apiclient._client.ContainerAlreadyExists: {\"description\": \"A specified external port is already in use.\"}\n", 
      "success": false
    }, 
    {
      "reason": "Traceback (most recent call last):\nFailure: twisted.internet.defer.FirstError: FirstError[#0, [Failure instance: Traceback: <class 'flocker.apiclient._client.ContainerAlreadyExists'>: {\"description\": \"A specified external port is already in use.\"}\n/home/richard/.venvs/benchmarking/local/lib/python2.7/site-packages/treq/client.py:62:connectionLost\n/home/richard/.venvs/benchmarking/local/lib/python2.7/site-packages/treq/content.py:38:connectionLost\n/home/richard/.venvs/benchmarking/local/lib/python2.7/site-packages/twisted/internet/defer.py:393:callback\n/home/richard/.venvs/benchmarking/local/lib/python2.7/site-packages/twisted/internet/defer.py:501:_startRunCallbacks\n--- <exception caught here> ---\n/home/richard/.venvs/benchmarking/local/lib/python2.7/site-packages/twisted/internet/defer.py:588:_runCallbacks\n/home/richard/flocker/flocker/apiclient/_client.py:624:error\n]]\n", 
      "success": false
    }, 
    {
      "value": 10.794026851654053, 
      "success": true
    }
  ], 
  "operation": {
    "type": "create-container", 
    "name": "create-container"
  }
}

```

The results show that some sample containers failed because they attempted to use already allocated ports.
But in the samples that succeeded, the container was running in ~10s.

### CODE REVIEW

**Comment by wallnerryan** [comment]
left a comment. https://clusterhq.atlassian.net/browse/FLOC-4487?focusedCommentId=28800&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-28800

Seems my comment is answered by the above, which is ~10s, but if we are hitting limits on already allocated ports, can we build into our benchmark scripts to choose open ports? Should be plenty of ports available.

**Comment by wallnerryan** [comment]
@wallrj do you have new results with the port mapping issue fixed for benchmarking?

Does this change seem to satisfy the slow container startup issue?

Also, seeing build failures for tests like `test_traffic_routed` and `test_linking` which i expect is an expected result of removing routing, but lets clean up the tests too so we don't see failures on un needed tests.

**Comment by wallnerryan** [comment]
did glance at seeing that nothing that wasn't supposed to be removed wasn't and a search on networking related code, im not familiar with the network/iptables implementation in flocker but it looks like anything left over related to network is either in provisioning code, rest api and some specifics to docker container inspecting but not for iptables nat. I trust that you've cleaned up the right bits. 

so mainly, clean up the network specific tests lingering around in https://github.com/ClusterHQ/flocker/blob/remove-linking-FLOC-4487/flocker/acceptance/obsolete/test_containers.py. Also looks like `flocker.acceptance.endtoend.test_dockerplugin.DockerPluginTests` is still failing on Trusty as in some other PRs.

**Comment by wallrj** [comment]
The failing Rackspace + Ubuntu 14.04 acceptance tests are caused by #2479

**Comment by wallnerryan** [comment]
woo, ~`-2000` lines. LGTM. Thanks for removing old network tests. Any update on benchmarks with container startup?

**Comment by wallrj** [comment]
> Any update on benchmarks with container startup? 

This branch allowed me to start a 100 node cluster with 2000 PostgreSQL  databases with exposed ports.

I didn't get a chance to repeat the container startup benchmark, but I'll do that on a pre-release branch after I merge this and the other bug fixes.

**Pull request merged**
