### PR TITLE
Build vagrant basebox floc 2494

### PR DESCRIPTION
**Pull request by Azulinho**
Add a new Vagrantfile for 'basebox' virtualbox VM
Update the Vagrantfile used by the buildbot job flocker-vagrant-dev to use the new basebox
disable tox tests using pypy

The first run of the modified flocker-vagrant-dev will fail until the PR https://github.com/ClusterHQ/build.clusterhq.com/pull/108 is merged and built once.

JIRA https://clusterhq.atlassian.net/browse/FLOC-2494

### CODE REVIEW

**Comment by tomprince** [comment]
It isn't clear to me how this is different from the existing dev-box? It looks like the dev-box is now just a repackaging of the basebox.

**Comment by Azulinho** [comment]
dev-box = basebox + tox tests.
But the build of dev-box doesn't build a vagrant image, simply consumes the most recent basebox image built.

**Comment by tomprince** [comment]
Well, then why call it the base-box and not the dev-box?

**Comment by tomprince** [comment]
That is, all we need to do is change when the dev-box gets built, not rename the dev-box and change when it is built.

**Comment by Azulinho** [comment]
if we do that, then we would be discarding all the tox tests that get executed. if they dont provide any value (cant answer if they do or not) then it may be simpler not to run them at all.

**Comment by tomprince** [comment]
> if we do that, then we would be discarding all the tox tests that get executed.

I don't follow. The name we give the box doesn't have anything to do with running the tests. Note that the tests aren't run by building the dev-box, but as a separate step afterwards.

**Comment by Azulinho** [comment]
oh sorry, I get what you are saying now.
yeap, you're right, no reason it is called basebox, can look into it so that it uses the vgtfile from the existing dev-box

**Pull request closed without merging**
