### PR TITLE
Fix Running MRO error:

### PR DESCRIPTION
**Pull request by moypray**
Traceback (most recent call last):
  File "/usr/local/bin/flocker-dataset-agent", line 7, in <module>
    from flocker.node.script import flocker_dataset_agent_main
  File "/usr/local/lib/python2.7/dist-packages/flocker/node/__init__.py", line 17, in <module>
    from .script import BackendDescription, DeployerType
  File "/usr/local/lib/python2.7/dist-packages/flocker/node/script.py", line 37, in <module>
    from ._loop import AgentLoopService
  File "/usr/local/lib/python2.7/dist-packages/flocker/node/_loop.py", line 395, in <module>
    class AgentLoopService(object, MultiService):
TypeError: Error when calling the metaclass bases
    Cannot create a consistent method resolution
order (MRO) for bases object, MultiService

### CODE REVIEW

**Comment by exarkun** [comment]
Thanks.

This is caused by an incompatible change made in a recent release of Twisted.  We test Flocker against a specific version of Twisted which doesn't contain this problem.  If you use any of the OS packages we distribute, you won't run into this problem because we include versions of our dependencies in those packages which we test against.  If you install Flocker using anything that respects Python's requirements metadata (either in setup.py or in our requirements.txt file) then you should also get the same version of Twisted that we test Flocker against.  So this should also avoid this (and similar) problems.

You can find detailed instructions about the recommended way to install Flocker from source (ie, not using the native OS packages) at <https://docs.clusterhq.com/en/1.1.0/install/install-client.html#other-linux-distributions>.  The instructions more or less come down to "install a couple native OS dependencies, make a virtualenv, use pip to install Flocker into it".

Since it looks like Twisted is going to stick with this incompatible change, Flocker will eventually need to change to be compatible with it.  The change in this PR looks like it's the right one for that.  We might hold off on merging this until we have testing in place on our CI system, though (letting us avoid introducing regressions into Flocker compatibility with the newer version of Twisted).

Thanks again.

**Comment by moypray** [comment]
Hi   @exarkun .  Thanks for your reply and explanation.

I am using Ubuntu 14.04, but it failed to install flocker following the way of in  https://docs.clusterhq.com/en/1.1.0/install/install-client.html

So I install it according to "other linux distribution", but I got lots of package dependency errors.
Finally I dropped using virtualenv, installing all the packages (pip install) which required by flocker, and this issue come up, but after this fix, it works, and I success to bring flocker up and could create container using flocker-deploy.

my python is: 2.7.6.
root@ubuntu:~# python --version
Python 2.7.6
root@ubuntu:~#

I am not sure why do not reproduce in your environment.

**Comment by exarkun** [comment]
Thanks for the follow-up moypray.  I'm curious about the errors you encountered when following <https://docs.clusterhq.com/en/1.1.0/install/install-client.html>.  I'd really like those instructions to work. :smile:

**Comment by moypray** [comment]
thanks,  I met the error is  the same with https://github.com/ClusterHQ/flocker/issues/1851

**Comment by jongiddy** [comment]
Can you please provide some more context about what you were doing when the problems occurred?

I'd like to clarify this, because the error in #1851 may occur when installing the package `clusterhq-flocker-node`, but the instructions at https://docs.clusterhq.com/en/1.1.0/install/install-client.html don't mention that package.

Did this problem occur while you were installing the Flocker client or installing a Flocker node?  Were you modifying the "Other Linux" instructions on the client installation page to install a Flocker node manually?

Thanks.

**Comment by moypray** [comment]
hi , @jongiddy, 

I just use "pip install https://clusterhq-archive.s3.amazonaws.com/python/Flocker-1.1.0-py2-none-any.whl" to install flocker.

source flocker-client/bin/activate
flocker-deploy  version    could work.

but when I try to start flocker-control (not using virtualenv) it does not work. so i use pip install some required package.
run flocker-control met this problem. after the fix, it works, and could run containers. and then submit this PR.

**Comment by itamarst** [comment]
`flocker-control` is not really intended to be installed this way, only the client, so it's not surprising it didn't work. It is surprising that you ended up with wrong version of Twisted, though, I tried following instructions locally and ended up with correct version...

Anyway I'll try to do a CI run on this and see if we can get it merged - thanks for the patch!

**Comment by adamtheturtle** [comment]
@moypray As per https://docs.clusterhq.com/en/1.1.0/gettinginvolved/contributing.html#id2 feel free to add your name to `AUTHORS.rst` and once this is merged get in touch for some swag.

**Comment by moypray** [comment]
@adamtheturtle  Update the PR, Am I right?  
I hope I could submit some PR on Flocker too. I am very interesting in it.

thanks

**Comment by moypray** [comment]
@adamtheturtle 
And more, Is there something about debuging flocker docs or wiki ?

Now I setup a control service on a Host,  and a node in another Host(Node B),  and Node B could run container success with flocker-plugin volumes.  but the local control service Node could work.

**Comment by adamtheturtle** [comment]
@moypray I will run this build when GitHub is no longer suffering from the DDOS attack (see https://status.github.com).

The latest released docs on debugging Flocker are at https://docs.clusterhq.com/en/1.1.0/using/administering/debugging.html. However those have been improved in `master` since the last release. We will be doing another release shortly and it will include a diagnostics tool.

**Comment by moypray** [comment]
@adamtheturtle  ok, thanks

**Comment by adamtheturtle** [comment]
@moypray First GitHub had problems, then PyPI, and now it turns out that your name and company set off our spellchecker! I have a Pull Request accepted (modulo tests passing) for the spellchecker to ignore the AUTHORS file at https://github.com/ClusterHQ/flocker/pull/1883. When that is merged (and GitHub is still having problems) then I will run the tests on this and continue tomorrow.

Thanks for your patience

**Comment by adamtheturtle** [comment]
The GitHub report is wrong, there is no Build pending for the vagrant/build/tutorial builder and a build already passed - http://build.clusterhq.com/boxes-flocker?branch=refs%2Fpull%2F1863%2Fhead. Thanks @moypray , I'll merge this. Remember to get in touch if you'd like some swag, and thanks again for your contribution.

**Pull request merged**
