### PR TITLE
[FLOC-1391] Release/flocker 0.3.3dev6

### PR DESCRIPTION
**Pull request by adamtheturtle**
DO NOT MERGE.

This branch should not be merged. See the explanation on the issue for why this is weird. Ignore the Files changed - they are being reviewed in another branch.

This followed the release process as built for this branch, not the release process for master, so it should be reviewed from there.

There were two changes made in order to make `admin/publish-docs --doc-version ${VERSION}` work:
* We made the change suggested https://github.com/ClusterHQ/flocker/pull/1120/files#r24503846
* We modified `dev_prefix` in `publish_docs` to remove `-dirty` from the string.

### CODE REVIEW

**Comment by adamtheturtle** [comment]
Buildbot has greyed out some builders. This is still the case after a build was forced (http://build.clusterhq.com/boxes-flocker?branch=release%2Fflocker-0.3.3dev6).

**Comment by adamtheturtle** [comment]
The review process says to check that:

> https://docs.staging.clusterhq.com/en/latest/authors.html should redirect to https://docs.staging.clusterhq.com/en/${VERSION}/authors.html

This doesn't work but we think that it is a typo and that it should instead be a check that https://docs.staging.clusterhq.com/en/devel/authors.html redirects. Notice the change between `latest` and `devel`.

**Comment by wallrj** [comment]
It's difficult to see what changes you made on top of @tomprince 's branch and master.
Perhaps if I create a new local branch from master and merge in maintenance-release-fixes-FLOC-1301
Then compare against that ???

**Comment by wallrj** [comment]
The `vagrant box add` step fails
```
[~/projects/HybridLogic]$ export VERSION=0.3.3dev6
[~/projects/HybridLogic]$ vagrant box add http://build.clusterhq.com/results/vagrant/release/flocker-${VERSION}/flocker-tutorial.json
A name is required when adding a box file directly. Please pass
the `--name` parameter to `vagrant box add`. See
`vagrant box add -h` for more help.
```
[~/projects/HybridLogic]$ curl http://build.clusterhq.com/results/vagrant/release/flocker-${VERSION}/flocker-tutorial.json

<html>
  <head><title>404 - No Such Resource</title></head>
  <body>
    <h1>No Such Resource</h1>
    <p>File not found.</p>
  </body>
</html>

```

Perhaps I need to force another vagrant-dev build?

**Comment by wallrj** [comment]
http://build.clusterhq.com/builders/flocker-vagrant-dev-box/builds/147/steps/build-base-box/logs/stdio

```
admin/build-vagrant-box --box dev --branch release/flocker-0.3.3dev6 --build-server http://build.clusterhq.com/
 in dir /home/buildslave/fedora-vagrant/flocker-vagrant-dev-box/build (timeout 1200 secs)
 watching logfiles {}
 argv: ['admin/build-vagrant-box', '--box', 'dev', '--branch', 'release/flocker-0.3.3dev6', '--build-server', 'http://build.clusterhq.com/']
 environment:
  HOME=/home/buildslave
  LANG=en_US.UTF-8
  LOGNAME=buildslave
  PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin
  PWD=/home/buildslave/fedora-vagrant/flocker-vagrant-dev-box/build
  SHELL=/bin/bash
  USER=buildslave
 using PTY: False
Traceback (most recent call last):
  File "admin/build-vagrant-box", line 12, in <module>
    from admin.vagrant import main
  File "/home/buildslave/fedora-vagrant/flocker-vagrant-dev-box/build/admin/vagrant.py", line 17, in <module>
    from admin.release import make_rpm_version
  File "/home/buildslave/fedora-vagrant/flocker-vagrant-dev-box/build/admin/release.py", line 10, in <module>
    from effect import (
ImportError: No module named effect
program finished with exit code 1
elapsedTime=0.109794
```

**Comment by wallrj** [comment]
Ah, sorry, I meant the vagrant-tutorial box builder. But it has the same error:
 * http://build.clusterhq.com/builders/flocker-vagrant-tutorial-box/builds/1076/steps/build-base-box/logs/stdio

```
admin/build-vagrant-box --box tutorial --branch release/flocker-0.3.3dev6 --build-server http://build.clusterhq.com/
 in dir /home/buildslave/fedora-vagrant/flocker-vagrant-tutorial-box/build (timeout 1200 secs)
 watching logfiles {}
 argv: ['admin/build-vagrant-box', '--box', 'tutorial', '--branch', 'release/flocker-0.3.3dev6', '--build-server', 'http://build.clusterhq.com/']
 environment:
  HOME=/home/buildslave
  LANG=en_US.UTF-8
  LOGNAME=buildslave
  PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin
  PWD=/home/buildslave/fedora-vagrant/flocker-vagrant-tutorial-box/build
  SHELL=/bin/bash
  USER=buildslave
 using PTY: False
Traceback (most recent call last):
  File "admin/build-vagrant-box", line 12, in <module>
    from admin.vagrant import main
  File "/home/buildslave/fedora-vagrant/flocker-vagrant-tutorial-box/build/admin/vagrant.py", line 17, in <module>
    from admin.release import make_rpm_version
  File "/home/buildslave/fedora-vagrant/flocker-vagrant-tutorial-box/build/admin/release.py", line 10, in <module>
    from effect import (
ImportError: No module named effect
program finished with exit code 1
elapsedTime=0.117141
```

**Comment by adamtheturtle** [comment]
> It's difficult to see what changes you made on top of @tomprince 's branch and master.

If you look at the list of commits you can see that they are all made by @tomprince apart from a merge of `master` into this branch. That merge included resolving a single, small conflict in the docs (prompt vs console).

The other things we did are not committed and in the description of this branch. They have been added as comments to resolve in the other branch.

**Comment by adamtheturtle** [comment]
After forcing a build the tutorial box builder passed. This means that the "Pre-tag Review Process" can continue - if the other buildbot issues are acceptable. These issues are: 3 test failures on `flocker/installed-package/fedora-20` and `flocker-vagrant-dev-box` not starting to build (even after a buildbot restart).

What do you think @wallrj ?

**Comment by adamtheturtle** [comment]
`flocker-vagrant-dev-box` needs a build to be forced. This has been done and it fails with the same failures as the other box. If these failures are known / acceptable, the review process can continue.

**Comment by itamarst** [comment]
The generated vagrant box does not have the expected version in its name. The version that matters is the one we set in the Hashicorp Atlas web UI, so this is not a big deal, but the problem also appears in user visible places, e.g.:

```
$ flocker-deploy --version
0.3.2+doc1-1591-g3c58069
```

Possibly this is fixed already in later version of release branch?

**Comment by itamarst** [comment]
Or perhaps this is because we haven't tagged it yet? And I'm just being stupid (with a little help from slightly misleading docs that will go away once buildbot can run vagrant, so never mind).

**Comment by adamtheturtle** [comment]
> Possibly this is fixed already in later version of release branch?

I believe that this is because the release branch being tested has not been tagged yet, and so the version will be "clean" at a later stage.

**Comment by itamarst** [comment]
`effect` still is not installing in local checkout off the release branch where I'm trying to run acceptance tests. This is confusing since the required version `0.1a13` appears to be available...

```
$ grep effect setup.py 
            "effect==0.1a13",
6$ pip install effect
Downloading/unpacking effect
  Could not find a version that satisfies the requirement effect (from versions: 0.1a1, 0.1a10, 0.1a11, 0.1a12, 0.1a13, 0.1a2, 0.1a3, 0.1a4, 0.1a5, 0.1a6, 0.1a7, 0.1a8, 0.1a9, 0.1a1, 0.1a10, 0.1a11, 0.1a12, 0.1a13, 0.1a2, 0.1a3, 0.1a4, 0.1a5, 0.1a6, 0.1a7, 0.1a8, 0.1a9)
```

**Comment by itamarst** [comment]
The release instructions don't mention need for `pip install --edit .[release]`. This is not a blocker, and should become unnecessary if buildbot can run acceptance tests.

**Comment by itamarst** [comment]
Acceptance tests passed.

**Comment by wallrj** [comment]
> Remove the Vagrant box which was added as part of Pre-tag Review Process:

This step doesn't work if you have multiple versions of the flocker-tutorial box installed.
```
(release/flocker-0.3.3dev6 ? =)[~/.../HybridLogic/flocker]$ vagrant box remove clusterhq/flocker-tutorial

You requested to remove the box 'clusterhq/flocker-tutorial' with provider
'virtualbox'. This box has multiple versions. You must
explicitly specify which version you want to remove with
the `--box-version` flag. The available versions for this
box are:

 * 0.3.2.1559.gca68f69
 * 0.3.2.doc1
 * 0.3.2.doc1.1666.gc6da06b
 * 0.3.2.doc2
```

**Comment by adamtheturtle** [comment]
@wallrj Good spot but this is now not a step in `master` so no fix is needed.

**Comment by wallrj** [comment]
> Check that the documentation is set up correctly:

Documentation links all seem to work.

**Comment by wallrj** [comment]
> The client (flocker-deploy) should be installed on all supported platforms

Verified  client installation
 * Fedora 20
 * Ubuntu 14.04
 * Mac OSX Yosemite.

**Comment by wallrj** [comment]
> The node package (flocker-node) should be installed on all supported platforms

 * Acceptance tests have passed on our vagrant tutorial based acceptance builder: http://build.clusterhq.com/builders/flocker%2Facceptance%2Fvagrant%2Ffedora-20/builds/558/steps/trial/logs/stdio
 * Installed successfully on a local Fedora20 box following the Fedora20 installation instructions.

...I give up for this evening.


TODO

* Run tutorial
```
node1: Downloading: https://atlas.hashicorp.com/clusterhq/boxes/flocker-tutorial/versions/0.3.3dev6/providers/virtualbox.box
    node1: Progress: 1% (Rate: 137k/s, Estimated time remaining: 1:27:54)

```


* Run cloud acceptance tests

```
(flocker-0.3.3dev6)(release/flocker-0.3.3dev6 ? =)[~/.../HybridLogic/flocker]$ ./admin/run-acceptance-tests --distribution fedora-20 --provider aws --config-file aws.config 
...
[root@52.10.132.15] out:   Installing : zfs-dkms-0.6.3-77_g5684a91.fc20.noarch [######################################## ] 21/28
[root@52.10.132.15] out:   Installing : zfs-dkms-0.6.3-77_g5684a91.fc20.noarch                                             21/28 
[root@52.10.132.15] out: 

```

**Comment by wallrj** [comment]
Errors when running AWS acceptance tests:

```
...
[root@52.10.132.15] out:   Installing : spl-dkms-0.6.3-10_g59edeca.fc20.noarch 
[root@52.10.132.15] out: Loading new spl-0.6.3 DKMS files...
[root@52.10.132.15] out: /usr/lib/dkms/common.postinst: line 123: which: command not found
[root@52.10.132.15] out: Building for 3.18.7-100.fc20.x86_64
[root@52.10.132.15] out: Building initial module for 3.18.7-100.fc20.x86_64
[root@52.10.132.15] out: /var/lib/dkms/spl/0.6.3/build/configure: line 6355: /usr/bin/file: No such file or directory
[root@52.10.132.15] out: Error! Bad return status for module build on kernel: 3.18.7-100.fc20.x86_64 (x86_64)
[root@52.10.132.15] out: Consult /var/lib/dkms/spl/0.6.3/build/make.log for more information.
[root@52.10.132.15] out: warning: %post(spl-dkms-0.6.3-10_g59edeca.fc20.noarch) scriptlet failed, exit status 10
[root@52.10.132.15] out: Non-fatal POSTIN scriptlet failure in rpm package spl-dkms-0.6.3-10_g59edeca.fc20.noarch
[root@52.10.132.15] out: 
...

[root@52.10.132.15] out:   Installing : zfs-dkms-0.6.3-77_g5684a91.fc20.noarch                                             21/28 
[root@52.10.132.15] out: Loading new zfs-0.6.3 DKMS files...
[root@52.10.132.15] out: /usr/lib/dkms/common.postinst: line 123: which: command not found
[root@52.10.132.15] out: Building for 3.18.7-100.fc20.x86_64
[root@52.10.132.15] out: Building initial module for 3.18.7-100.fc20.x86_64
[root@52.10.132.15] out: /var/lib/dkms/zfs/0.6.3/build/configure: line 6503: /usr/bin/file: No such file or directory
[root@52.10.132.15] out: configure: error: 
[root@52.10.132.15] out: 	*** Please make sure the kmod spl devel <kernel> package for your
[root@52.10.132.15] out: 	*** distribution is installed then try again.  If that fails you
[root@52.10.132.15] out: 	*** can specify the location of the spl objects with the
[root@52.10.132.15] out: 	*** '--with-spl-obj=PATH' option.
[root@52.10.132.15] out: Error! Bad return status for module build on kernel: 3.18.7-100.fc20.x86_64 (x86_64)
[root@52.10.132.15] out: Consult /var/lib/dkms/zfs/0.6.3/build/make.log for more information.
[root@52.10.132.15] out: warning: %post(zfs-dkms-0.6.3-77_g5684a91.fc20.noarch) scriptlet failed, exit status 10
[root@52.10.132.15] out: Non-fatal POSTIN scriptlet failure in rpm package zfs-dkms-0.6.3-77_g5684a91.fc20.noarch
[root@52.10.132.15] out: 
...

[root@52.10.132.15] run: zpool create flocker /var/opt/flocker/pool-vdev
[root@52.10.132.15] out: Failed to load ZFS module stack.
[root@52.10.132.15] out: Load the module manually by running 'insmod <location>/zfs.ko' as root.
[root@52.10.132.15] out: 


Fatal error: run() received nonzero return code 1 while executing!

Requested: zpool create flocker /var/opt/flocker/pool-vdev
Executed: /bin/bash -l -c "zpool create flocker /var/opt/flocker/pool-vdev"

Aborting.
Destroying acceptance-test-richardw-0

```

**Comment by wallrj** [comment]
AWS acceptance tests fail: https://clusterhq.atlassian.net/browse/FLOC-1455

**Comment by adamtheturtle** [comment]
The review process does not include running the cloud acceptance tests yet, but I guess that means that the manual process would fail too. I'm guessing that you followed the WIP instructions on https://github.com/ClusterHQ/flocker/pull/1043/files.

I suggest that the rest of the review is done (if it hasn't been done already) and any follow up issues are created and made to be blockers to https://clusterhq.atlassian.net/browse/FLOC-1436 while this PR is closed and its parent issue thrown away.

Thank you for doing the temporarily-painful review process.

**Comment by wallrj** [comment]
We decided to abandon this release after the AWS cloud acceptance failures.

**Pull request closed without merging**
