### PR TITLE
pin pyasn1-modules

### PR DESCRIPTION
**Pull request by exarkun**
Fixes https://clusterhq.atlassian.net/browse/FLOC-2506

See #1706 for comments on the approach.

### CODE REVIEW

**Comment by adamtheturtle** [comment]
Thanks @exarkun - this seems like an improvement to me. However, I am wary of @tomprince 's concerns that pinning security modules is a risk. Maybe we should look at https://clusterhq.atlassian.net/browse/FLOC-1172 soon.

**Comment by adamtheturtle** [comment]
Merge when you're happy (I guess now, this is a test fixer so it can be merged, right?).

**Comment by exarkun** [comment]
> However, I am wary of @tomprince 's concerns that pinning security modules is a risk.

In general I agree with this concern.  So yea, we should do something better.  For this particular case, I'm not as concerned because our use of pyasn1 is in our build infrastructure only.

**Comment by exarkun** [comment]
I am unhappy with the outcome of the builds:

  * installed-package/vagrant/centos-7 - hung, known issue, https://clusterhq.atlassian.net/browse/FLOC-2503
  *  acceptance/vagrant/centos-7/zfs
    * failed container tests, known issue, https://clusterhq.atlassian.net/browse/FLOC-2488
    * failed postgres tests, known issue (can't find the issue but I know it's filed)
  * Rackspace builders - Resource limits exceeded, known issue, https://clusterhq.atlassian.net/browse/FLOC-2441
  * acceptance/aws/ubuntu-14.04/aws - Resource limits exceeded, known issue, https://clusterhq.atlassian.net/browse/FLOC-2441

So I guess I'll merge.

**Pull request merged**
