### PR TITLE
[FLOC-3404] Release improvements

### PR DESCRIPTION
**Pull request by dwgebler**
Improve the release process, automate more of it, make less steps.
Fixes FLOC-3404.

Docs build for modified release instructions:
http://build.clusterhq.com/results/docs/release-improvements-FLOC-3404/build-11077/gettinginvolved/infrastructure/release-process.html

[Review on Reviewable](https://reviewable.io/reviews/clusterhq/flocker/2147)

### CODE REVIEW

**Comment by jml** [comment]
Thanks! 

A few questions & a couple of things to clean up. Please resubmit (and feel free to ping me on slack when you do so).


---

Reviewed 3 of 3 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

<sup>**[admin/release.py, line 797 \[r1\]](https://reviewable.io:443/reviews/clusterhq/flocker/2147#-K2gpe_bZP8bSGhpMjr-)** ([raw file](https://github.com/clusterhq/flocker/blob/9a18bbdadb7915d6c4fb8743627414b10a7fa2a7/admin/release.py#L797)):</sup>
Is this actually true? Don't we sometimes do releases where we fix up something critical in a release branch?


---

<sup>**[admin/release.py, line 868 \[r1\]](https://reviewable.io:443/reviews/clusterhq/flocker/2147#-K2gr9Ft0rOwSCRqlMkr)** ([raw file](https://github.com/clusterhq/flocker/blob/9a18bbdadb7915d6c4fb8743627414b10a7fa2a7/admin/release.py#L868)):</sup>
:grey_question: Strongly consider factoring everything below this into a separate function, `initialize_release`, that takes `version`, `path`, and `top_level` as parameters. 


---

<sup>**[admin/release.py, line 869 \[r1\]](https://reviewable.io:443/reviews/clusterhq/flocker/2147#-K2gqCq7lU_uLhtxPuyv)** ([raw file](https://github.com/clusterhq/flocker/blob/9a18bbdadb7915d6c4fb8743627414b10a7fa2a7/admin/release.py#L869)):</sup>
Please delete commented-out code.


---

<sup>**[admin/release.py, line 871 \[r1\]](https://reviewable.io:443/reviews/clusterhq/flocker/2147#-K2gq6NVy8HlEBS7TVH4)** ([raw file](https://github.com/clusterhq/flocker/blob/9a18bbdadb7915d6c4fb8743627414b10a7fa2a7/admin/release.py#L871)):</sup>
Why are you doing `sys.stdout.write` rather than `print`?


---

<sup>**[admin/release.py, line 872 \[r1\]](https://reviewable.io:443/reviews/clusterhq/flocker/2147#-K2gqEww_nFMEC15EKv0)** ([raw file](https://github.com/clusterhq/flocker/blob/9a18bbdadb7915d6c4fb8743627414b10a7fa2a7/admin/release.py#L872)):</sup>
Please delete commented-out code.


---

<sup>**[admin/release.py, line 877 \[r1\]](https://reviewable.io:443/reviews/clusterhq/flocker/2147#-K2gqcmuPX1SFEFtp_BX)** ([raw file](https://github.com/clusterhq/flocker/blob/9a18bbdadb7915d6c4fb8743627414b10a7fa2a7/admin/release.py#L877)):</sup>
I think it would make this easier to follow if you put a blank line before each of these announcements. It would help divide this long function up into natural stanzas.


---

<sup>**[admin/release.py, line 909 \[r1\]](https://reviewable.io:443/reviews/clusterhq/flocker/2147#-K2gqNDbDisrVn5RZpzH)** ([raw file](https://github.com/clusterhq/flocker/blob/9a18bbdadb7915d6c4fb8743627414b10a7fa2a7/admin/release.py#L909)):</sup>
Are we sure this is the only case where it will happen? Is it possible that this will mask more serious errors?


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/clusterhq/flocker/2147)

**Comment by dwgebler** [comment]
<sup>**[admin/release.py, line 797 \[r1\]](https://reviewable.io:443/reviews/clusterhq/flocker/2147#-K2gpe_bZP8bSGhpMjr-)** ([raw file](https://github.com/clusterhq/flocker/blob/9a18bbdadb7915d6c4fb8743627414b10a7fa2a7/admin/release.py#L797)):</sup>
We might base a release off something other than master, i.e. another release branch, but only when something's gone wrong - which means the regular release instructions aren't reliable in such rare cases anyway. We're supposed to now do regular releases off master and have dropped pre-releases.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/clusterhq/flocker/2147)

**Comment by dwgebler** [comment]
<sup>**[admin/release.py, line 868 \[r1\]](https://reviewable.io:443/reviews/clusterhq/flocker/2147#-K2gr9Ft0rOwSCRqlMkr)** ([raw file](https://github.com/clusterhq/flocker/blob/9a18bbdadb7915d6c4fb8743627414b10a7fa2a7/admin/release.py#L868)):</sup>
Will do!


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/clusterhq/flocker/2147)

**Comment by dwgebler** [comment]
<sup>**[admin/release.py, line 871 \[r1\]](https://reviewable.io:443/reviews/clusterhq/flocker/2147#-K2gq6NVy8HlEBS7TVH4)** ([raw file](https://github.com/clusterhq/flocker/blob/9a18bbdadb7915d6c4fb8743627414b10a7fa2a7/admin/release.py#L871)):</sup>
No special reason other than it's a habit from writing tests where sys might be parameterised for a fake.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/clusterhq/flocker/2147)

**Comment by dwgebler** [comment]
<sup>**[admin/release.py, line 909 \[r1\]](https://reviewable.io:443/reviews/clusterhq/flocker/2147#-K2gqNDbDisrVn5RZpzH)** ([raw file](https://github.com/clusterhq/flocker/blob/9a18bbdadb7915d6c4fb8743627414b10a7fa2a7/admin/release.py#L909)):</sup>
The particular exception is raised if the preceding commit command returns a non-zero exit code, which is what will happen if there is no diff to commit (exit code 1). We could potentially narrow this down further, but I don't think the risk of it coming up for some other reason is high enough to make it worth doing....not much serious can go wrong with attempting to commit here.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/clusterhq/flocker/2147)

**Comment by dwgebler** [comment]
<sup>**[admin/release.py, line 909 \[r1\]](https://reviewable.io:443/reviews/clusterhq/flocker/2147#-K2gqNDbDisrVn5RZpzH)** ([raw file](https://github.com/clusterhq/flocker/blob/9a18bbdadb7915d6c4fb8743627414b10a7fa2a7/admin/release.py#L909)):</sup>
(we have an admin test that will fail in the event that anything else that caused this exception meant the licence file didn't get updated when it needed to be)


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/clusterhq/flocker/2147)

**Comment by jml** [comment]
Thanks!


---

Reviewed 3 of 3 files at r1, 1 of 1 files at r2, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

<sup>**[admin/release.py, line 871 \[r1\]](https://reviewable.io:443/reviews/clusterhq/flocker/2147#-K2gq6NVy8HlEBS7TVH4)** ([raw file](https://github.com/clusterhq/flocker/blob/9a18bbdadb7915d6c4fb8743627414b10a7fa2a7/admin/release.py#L871)):</sup>
:grey_question: OK. I'd suggest either changing to `print` or adding an `output` parameter that defaults to `sys.stdout`. Now that there's more whitespace though, I think it's less important, so up to you whether to bother.


---

<sup>**[admin/release.py, line 909 \[r1\]](https://reviewable.io:443/reviews/clusterhq/flocker/2147#-K2gqNDbDisrVn5RZpzH)** ([raw file](https://github.com/clusterhq/flocker/blob/9a18bbdadb7915d6c4fb8743627414b10a7fa2a7/admin/release.py#L909)):</sup>
OK. Having an admin test is a good cover. Thanks.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/clusterhq/flocker/2147)

**Pull request merged**
