### PR TITLE
[FLOC-2484] Make padding top and bottom the same on headers

### PR DESCRIPTION
**Pull request by msh100**
Fixes FLOC-2484

### CODE REVIEW

**Comment by adamtheturtle** [comment]
To confirm, this is because A is longer than B, right?

screenshot 2015-06-22 14 02 56

**Comment by adamtheturtle** [comment]
If so I can't tell, but then the rest of the theme hasn't been through such scrutiny - the code is fine and the header looks fine to me and I'll leave it to your judgement. If the issue is something else then resubmit.

**Comment by msh100** [comment]
Thanks @adamtheturtle, I think you're looking at the wrong part of the page. This is likely due to a poor description in JIRA.

http://i.imgur.com/pT5HyuT.png

On the left is the new version, the right is what we currently have.

The change is to increase the top padding for content headers.

**Comment by adamtheturtle** [comment]
Ok, same comment applies, thanks. Merging.

**Pull request merged**
