### PR TITLE
[FLOC-3032] Re-install flocker-docker-plugin on acceptance test upgrades

### PR DESCRIPTION
**Pull request by exarkun**
Fixes https://clusterhq.atlassian.net/browse/FLOC-3032

[Review on Reviewable](https://reviewable.io/reviews/clusterhq/flocker/1936)

### CODE REVIEW

**Comment by dwgebler** [comment]
LGTM subject to builds passing. Several builds failed but they all look coincidental, a mix of known intermittent failures, I am re-running them.

**Comment by wallrj** [comment]
Forced another rebuild on two builds that failed.

**Comment by wallrj** [comment]
Ah, I think @itamarst may have done separate docker plugin installation to avoid adding it to the docs (until the flocker-docker-plugin is officially released)
 * See http://build.clusterhq.com/results/docs/reinstall-flocker-docker-plugin-FLOC-3032/build-9999/install/install-node.html#installing-on-centos-7

**Comment by itamarst** [comment]
Well, it's about to be official once docs branch is merged. But I think Docker plugin installation is maybe something that should be optional, yeah, in which case putting it here is problematic, yeah. In particular it'll be installed but broken because it's missing a certificate file.

**Comment by dwgebler** [comment]
:question: We could make a reasonably small change to introduce the concept of a "private" provisioning step in a task that does not get processed through the Sphinx extension.

**Comment by adamtheturtle** [comment]
> :question: We could make a reasonably small change to introduce the concept of a "private" provisioning step in a task that does not get processed through the Sphinx extension.

We already have used this before. See for example `locker.provision._install.ensure_minimal_setup` and its use.

**Pull request closed without merging**
