### PR TITLE
[FLOC-2290] Don't use world-writeable permissions if dataset has been modified with files

### PR DESCRIPTION
**Pull request by wallrj**
Fixes: https://clusterhq.atlassian.net/browse/FLOC-2290

Merged 80f4df5c9b4a0dc310ec22618a243cf5a754aef8 (PR #1606) into master.

### CODE REVIEW

**Comment by exarkun** [comment]
This includes unrelated changes.

**Comment by wallrj** [comment]
This was stacked on a branch which has now been merged (#1627).

**Comment by itamarst** [comment]
Merge when buildbot is happy.

**Comment by wallrj** [comment]
The test failures were caused by Rackspace resource and api limits. 

So I merged anyway.

**Pull request merged**
