### PR TITLE
Adjust copyright headers.

### PR DESCRIPTION
**Pull request by tomprince**
https://clusterhq.atlassian.net/browse/FLOC-3519

### CODE REVIEW

**Comment by sarum90** [comment]
Looks like you did this correctly as far as I can tell -- Thanks! nice to clean up low hanging fruit like this.

I think this is a fine thing to do with all of these files? I've certainly seen it done on several in other code reviews. I'm still not 100% I know the ramifications of changing these, so I will accept the review, but I'll leave it for you to merge.

**Comment by tomprince** [comment]
I've checked with the appropriate people, and will merge once I hear back from them.

**Comment by jongiddy** [comment]
Shouldn't the copyright notice include the years in which the file has been modified? https://en.wikipedia.org/wiki/Copyright_notice

**Comment by tomprince** [comment]
> Shouldn't the copyright notice include the years in which the file has been modified? https://en.wikipedia.org/wiki/Copyright_notice

I've asked about this, but am going to merge this as an incremental improvement.

**Pull request merged**
