### PR TITLE
[FLOC-2121] Remove fedora20 floc 2121

### PR DESCRIPTION
**Pull request by adamtheturtle**
Fixes https://clusterhq.atlassian.net/browse/FLOC-2121

I'm hoping that nothing else uses this Dockerfile. The test runner should tell us.

### CODE REVIEW

**Comment by jongiddy** [comment]
`test_release.py` now contains a few references to Fedora, but `release.py` has none. I suggest changing remaining 'fedora' to 'centos'. Conveniently, the OS version number for these tests is 7, so this will work out well.

**Comment by jongiddy** [comment]
There is a comment in `release.py` that mentions Fedora, along with CentOS. This can be removed.

**Comment by jongiddy** [comment]
OK to merge

**Comment by wallrj** [comment]
I removed the DockerHub automated build which had been failing since this branch landed: https://hub.docker.com/r/clusterhq/build-fedora-20/~/settings/automated-builds/

**Pull request merged**
