### PR TITLE
[FLOC-3012] Pin Ubuntu version for dependencies, to prevent apt conflicts

### PR DESCRIPTION
**Pull request by jongiddy**
Currently, trying to run the client or acceptance tests for Flocker versions other than the latest version fails on Ubuntu, due to `apt` wanting to install the latest dependency rather than the requested dependency. e.g. running `admin/run-client-tests --distribution ubuntu-15.04 --flocker-version=1.2.0.dev1` fails with:
```
The following packages have unmet dependencies:
 clusterhq-flocker-cli : Depends: clusterhq-python-flocker (= 1.2.0-0.dev.1) but 1.4.0-0.dev.1 is to be installed
E: Unable to correct problems, you have held broken packages.
```

This PR pins the version for any dependencies starting with `clusterhq-` to the same as the top-level package. Currently, the only such dependency is `clusterhq-python-flocker` which always must match the version number of the top-level packages.

As well as working for the above release version, it also works for branches: `admin/run-client-tests --distribution ubuntu-14.04 --branch master --flocker-version=1.4.0.dev1+10.gf9dea05` installs an previous version of the client from Buildbot.

[Review on Reviewable](https://reviewable.io/reviews/clusterhq/flocker/1925)

### CODE REVIEW

**Comment by Azulinho** [comment]
Dude John,
The tests are failling in the vagrant builds

```
==> default: No package clusterhq-flocker-node-1.4.0-0.dev.1.64.g56cb8ae available.
==> default: Error: Nothing to do
==> default: Traceback (most recent call last):
==> default:   File "/tmp/vagrant-shell", line 64, in <module>
==> default:     check_call(['yum', 'install', '-y'] + branch_opt + [package])
==> default:   File "/usr/lib64/python2.7/subprocess.py", line 542, in check_call
==> default:     raise CalledProcessError(retcode, cmd)
==> default: subprocess.CalledProcessError: Command '['yum', 'install', '-y', '--enablerepo=clusterhq-build', 'clusterhq-flocker-node-1.4.0-0.dev.1.64.g56cb8ae']' returned non-zero exit status 1
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
Failed 1: vagrant up
```
but this change also breaks the client tests on Jenkins
see:
http://52.88.192.98:8080/job/ClusterHQ-flocker/job/check-release-packages-FLOC-2770/

in detail:
http://52.88.192.98:8080/job/ClusterHQ-flocker/job/check-release-packages-FLOC-2770/job/run_client_installation_on_Ubuntu_Trusty/1/console
and
http://52.88.192.98:8080/job/ClusterHQ-flocker/job/check-release-packages-FLOC-2770/job/run_client_installation_on_Ubuntu_Vivid/1/console

```

18:52:06 ++ flocker-deploy --version
18:52:06 + test 1.4.0.dev1+77.ga9de306 = 1.4.0.dev1
18:52:06 + return 1
```

I don't see how this one could be related, it looks like the acceptance.yaml has changed, but I will post it here:
http://52.88.192.98:8080/job/ClusterHQ-flocker/job/check-release-packages-FLOC-2770/job/run_acceptance_on_AWS_CentOS_7_for_flocker.acceptance.integration.test_postgres/1/console

http://52.88.192.98:8080/job/ClusterHQ-flocker/job/check-release-packages-FLOC-2770/job/run_acceptance_on_AWS_Ubuntu_Trusty_for_flocker.acceptance.endtoend.test_dataset/1/console

http://52.88.192.98:8080/job/ClusterHQ-flocker/job/check-release-packages-FLOC-2770/job/run_acceptance_on_AWS_Ubuntu_Trusty_for_flocker.acceptance.integration.test_mongodb/1/console

```

18:44:53 main function encountered error
18:44:53 Traceback (most recent call last):
18:44:53   File "admin/run-acceptance-tests", line 14, in <module>
18:44:53     react(main, (sys.argv[1:], BASEPATH, TOPLEVEL))
18:44:53   File "/tmp/v/lib/python2.7/site-packages/twisted/internet/task.py", line 875, in react
18:44:53     finished = main(_reactor, *argv)
18:44:53   File "/tmp/v/lib/python2.7/site-packages/twisted/internet/defer.py", line 1253, in unwindGenerator
18:44:53     return _inlineCallbacks(None, gen, Deferred())
18:44:53 --- <exception caught here> ---
18:44:53   File "/tmp/v/lib/python2.7/site-packages/twisted/internet/defer.py", line 1107, in _inlineCallbacks
18:44:53     result = g.send(result)
18:44:53   File "/tmp/workspace/ClusterHQ-flocker/check-release-packages-FLOC-2770/run_acceptance_on_AWS_CentOS_7_for_flocker.acceptance.integration.test_postgres/admin/acceptance.py", line 921, in main
18:44:53     yield runner.ensure_keys(reactor)
18:44:53   File "/tmp/workspace/ClusterHQ-flocker/check-release-packages-FLOC-2770/run_acceptance_on_AWS_CentOS_7_for_flocker.acceptance.integration.test_postgres/admin/acceptance.py", line 534, in ensure_keys
18:44:53     key = self.provisioner.get_ssh_key()
18:44:53   File "/tmp/workspace/ClusterHQ-flocker/check-release-packages-FLOC-2770/run_acceptance_on_AWS_CentOS_7_for_flocker.acceptance.integration.test_postgres/flocker/provision/_libcloud.py", line 185, in get_ssh_key
18:44:53     raise CloudKeyNotFound(self._keyname)
18:44:53 flocker.provision._libcloud.CloudKeyNotFound: vagrant-buildbot

```

**Comment by jongiddy** [comment]
The tests on Jenkins might need to be changed similarly to https://github.com/ClusterHQ/build.clusterhq.com/pull/140

**Comment by jongiddy** [comment]
Resubmitting this, as none of the tests noted as failing appear to be due to this patch.

On OS X, the client tests may fail due to https://clusterhq.atlassian.net/browse/FLOC-3044 but this is also the case for `master`.

**Comment by jml** [comment]
:+1:

**Comment by adamtheturtle** [comment]
@jongiddy can this also close https://clusterhq.atlassian.net/browse/FLOC-2923?

**Comment by jongiddy** [comment]
@adamtheturtle I believe it should, as Buildbot tests are always runs with the Flocker version specified. Even if a new build gets triggered, the previous test should use the earlier dependency.

**Comment by adamtheturtle** [comment]
great

**Pull request merged**
