### PR TITLE
[FLOC 2716] Move authentication doc into Post-Install Config doc

### PR DESCRIPTION
**Pull request by davidoliverSP2**
Fixes 2716 (and duplicate 2343)

### CODE REVIEW

**Comment by itamarst** [comment]
I'm not sure this is the best organizational scheme for this bit... in particular it's a bit tricky to find, since it's deep in. How about splitting what you have now into multiple pages or something? So install section ends up with following pages:

* Installing the client
* Installing the Node services
* Configuring authentication
* Configuring nodes and storage backends
* Enabling and running the services

**Comment by davidoliverSP2** [comment]
Thanks @itamarst 

Looking at this again, I agree - I think your comment reflects the original plan for FLOC 2644, but I was trying to split the work into smaller step-changes in order to make the code review process more manageable.

**Comment by davidoliverSP2** [comment]
@itamarst 

What I would like to do is merge this PR, which moves the Authentication doc out of the Using section. Then I have created FLOC 2745 (as another subtask of 2644) to move the content out of the Post-Installation Configuration topic into smaller, more specific docs, as you described above.

**Comment by itamarst** [comment]
Sounds good, merge when buildbot is happy.

**Pull request merged**
