### PR TITLE
FLOC-4215 Tests for GCE driver race/error conditions

### PR DESCRIPTION
**Pull request by sarum90**
There were some specific race conditions within the GCE driver that are not exercised by the IBlockDeviceAPI tests. This separates the atomic operations GCE supports from the implementation of IBlockDeviceAPI, which enables a point to inject code (either right before or right after an atomic operation).

In thinking about the problem, most of the desired race conditions are exercised by simply calling the API call once right before the call done by the driver.

For instance, in order to get the undesirable race in detach_volume (the disk is detached after the listing call that determines where the disk was attached to, and before the call to detach) you just need to run detach once, right before the real call to detach.

Similar error conditions can be forced for creating, attaching, and destroying a volume.

This adds a simple test that just goes through a simple happy-case lifecycle of a volume, verifying that a driver that is doing things in a manner where it is just losing races to some outside agent returns the correct error.

### CODE REVIEW

**Comment by sarum90** [comment]
Functional tests on Jenkins can be found at http://ci-live.clusterhq.com:8080/job/ClusterHQ-flocker/job/gce-driver-race-conditions-FLOC-4215/job/_run_trial_for_gce_storage_driver_on_CentOS_7_flocker.node.agents.functional/ and http://ci-live.clusterhq.com:8080/job/ClusterHQ-flocker/job/gce-driver-race-conditions-FLOC-4215/job/_run_trial_for_gce_storage_driver_on_Ubuntu_trusty_flocker.node.agents.functional/

**Comment by wallrj** [comment]
Thanks @sarum90 

As discussed in the office, I'm not convinced that the extra complexity of the proxyForInterface is worth the benefit of testing these race conditions.
 * If you choose to land this branch maybe change the Interface name from `IGCEAtomicOperations` to  `IGCEVolumeManager` which is more in line with the `ICinderVolumeManager` in cinder.py
 * I personally think we should deprecate the ``AlreadyAttachedVolume``, ``UnknownVolume``, ``UnattachedVolume`` from all the drivers and trust the blockdevice deployer to make the correct calculations.

Consider the above and feel free to merge when green.

I notice there are some test failures on Jenkins and I'm running the tests manually.

**Comment by wallrj** [comment]
```
===============================================================================
[FAIL]
Traceback (most recent call last):
Failure: testtools.testresult.real._StringException: Empty attachments:
  twisted-log

twisted-eliot-log: {{{
0436299e-e237-4ab0-98d9-e009d89f5c4f -> /1
2016-02-26 22:10:06.839403Z
  action_type: 'agent:blockdevice:cleanup:details'
  action_status: 'started'

0436299e-e237-4ab0-98d9-e009d89f5c4f -> /2
2016-02-26 22:10:37.949362Z
  action_type: 'agent:blockdevice:cleanup:details'
  action_status: 'succeeded'
}}}

Traceback (most recent call last):
  File "/home/richard/flocker/flocker/node/agents/test/test_blockdevice.py", line 4016, in test_detach_volume
    self.assertNotEqual(attached_error, detached_error)
  File "/home/richard/.virtualenvs/flocker/local/lib/python2.7/site-packages/unittest2/case.py", line 845, in assertNotEqual
    raise self.failureException(msg)
AssertionError: 'mount: only root can do that\n' == 'mount: only root can do that\n'


flocker.node.agents.functional.test_gce.GCEBlockDeviceAPIInterfaceTests.test_detach_volume
===============================================================================
[ERROR]
Traceback (most recent call last):
Failure: testtools.testresult.real._StringException: Empty attachments:
  twisted-log

twisted-eliot-log: {{{
21046481-eeda-4ca2-bfb0-2f05fb0192be -> /1
2016-02-26 22:17:51.017289Z
  action_type: 'agent:blockdevice:cleanup:details'
  action_status: 'started'

21046481-eeda-4ca2-bfb0-2f05fb0192be -> /2
2016-02-26 22:17:51.017918Z
  action_type: 'agent:blockdevice:cleanup:details'
  action_status: 'succeeded'
}}}

Traceback (most recent call last):
  File "/home/richard/flocker/flocker/node/agents/functional/test_gce.py", line 160, in test_attach_elsewhere_attached_volume
    other_instance = gce_fixture.create_instance(instance_name)
  File "/home/richard/flocker/flocker/node/agents/functional/test_gce.py", line 79, in create_instance
    machine_type=u"f1-micro"
  File "/home/richard/flocker/flocker/provision/_gce.py", line 466, in create_instance
    self.compute, operation, timeout_steps=[1]*60)
  File "/home/richard/flocker/flocker/node/agents/gce.py", line 181, in wait_for_operation
    return poll_until(finished_operation_result, timeout_steps)
  File "/home/richard/flocker/flocker/common/_retry.py", line 240, in poll_until
    raise LoopExceeded(predicate, result)
flocker.common._retry.LoopExceeded: <function finished_operation_result at 0x7f2a16c68050> never True in loop_until, last result: None


flocker.node.agents.functional.test_gce.GCEBlockDeviceAPITests.test_attach_elsewhere_attached_volume
-------------------------------------------------------------------------------
Ran 29 tests in 716.520s

FAILED (failures=1, errors=1, successes=27)
```

Probably need a skip for non-root users and I'm not sure what caused the timeout.

**Comment by wallrj** [comment]
I ran the tests manually as root and found a couple of errors. Here are the details:
 * https://gist.github.com/wallrj/15e87d8dadf9973ea686#file-as-root

**Comment by sarum90** [comment]
I'm going to suspend this branch until everything else is landed in GCE (and potentially indefinitely). We have a lot of things outstanding right now, and this will merge conflict with all of them.

Given your doubts about the usefulness of this, I'm not going to push the burden of merging onto Brendan, who has some outstanding PRs.

The one thing that this testing caught, that I think we should add is there is that errors in detaching are currently not reported. I think we should probably raise some sort of error if the API returns an error condition. Now that I remembered that I probably will merge some form of this PR in... but not till other GCE work has concluded.

Thanks for the review though!

**Comment by sarum90** [comment]
I'm going to try to revive this branch, it provides a good place to add locking, which is evidently needed since the GCE client code is not threadsafe.  I'll be openning a new PR though because I need to merge it into the GCE staging branch.

**Comment by sarum90** [comment]
Closing in favor of #2706 Which is against the GCE staging branch.

**Pull request closed without merging**
