### PR TITLE
[FLOC-3010] Accurate device path for Cinder volumes

### PR DESCRIPTION
**Pull request by jongiddy**
Merging Cinder device fix into master.

This was a bit tricky because of a conflict in `flocker/acceptance/testtools.py`.  This PR removes the use of `REALISTIC_BLOCKDEVICE_SIZE` in function `create_dataset`, while another change adds a `dataset_id` parameter to that function.  Since this removed the import of `REALISTIC_BLOCKDEVICE_SIZE` from the `flocker.acceptance.testtools` file, the `test_leases` module needed to be changed to import it from it's actual source, the `flocker.testtools` module.

[Review on Reviewable](https://reviewable.io/reviews/clusterhq/flocker/1941)

### CODE REVIEW

**Comment by jongiddy** [comment]
GitHub has screwed the PR page up (for me at least). There should be ~13 commits for this PR, not 94.

**Comment by exarkun** [comment]
Unfortunately I can't figure out how to see the changes that are actually meant to be part of this PR in order to review them.

**Comment by jongiddy** [comment]
Closing this PR due to excessive commits. Will try creating a new PR.

**Comment by jongiddy** [comment]
See #1946 for updated PR.

**Pull request closed without merging**
