### PR TITLE
[FLOC-1300] Release Flocker 0.3.2+doc1

### PR DESCRIPTION
**Pull request by tomprince**
https://clusterhq.atlassian.net/browse/FLOC-1300

Pre-tag Review Checklist
- [ ] Do the acceptance tests. (although perhaps this can be skipped, as no changes were made to the running code)
- [x] Check documentation.
  - [x] The documentation should be available at https://docs.staging.clusterhq.com/en/0.3.2/
  - [x] The following URLs should redirect to the above URL.
     - https://docs.staging.clusterhq.com/
     - https://docs.staging.clusterhq.com/en/
     - https://docs.staging.clusterhq.com/en/latest/
 
    In addition, check that deep-links to /en/latest/ work. https://docs.staging.clusterhq.com/en/latest/authors.html should redirect to https://docs.staging.clusterhq.com/en/0.3.2/authors.html
- [ ] Additional checks, since this is the first release on s3:
   - Check that, for all versions on [readthedocs](https://readthedocs.org/projects/flocker/), we redirect to the latest version, both for the root, and for deep links.

I'm not sure the above list is exhaustive.

The branch should not be merged until the release process is complete.

### CODE REVIEW

**Comment by tomprince** [comment]
I'm not sure the cloudfront invalidation is fixed. But I guess everybody else is hitting a different edge node, so my testing requests shouldn't be cached for anybody else.

**Comment by tomprince** [comment]
Also, I used the staging buildbot to upload the docs this time around.

**Comment by tomprince** [comment]
The diff or commits aren't an accurate portrayal of what should be reviewed. The plan is to tag https://github.com/ClusterHQ/flocker/commit/2c44aa71b530493e00546f0edb9a2a1edcb55924 as `0.3.2+doc1`. https://github.com/ClusterHQ/flocker/compare/0.3.2...2c44aa71b530493e00546f0edb9a2a1edcb55924 is all the changes since `0.3.2`, but those have all been reviewed. And everything has been merged to master. There are no changes specific to this doc release, as there is nothing significant to add to the release notes, and no version numbers to change in the documentation.

**Comment by exarkun** [comment]
Thanks.  Unfortunately, I'm pretty confused.  The explanation sounds like there will be no text changes introduced into master by this merge.  If that's the case ... why is there a PR?  Is it just as a placeholder to satisfy the documented release process?  Or a helper to get buildbot to do the right thing (but buildbot won't do the right thing since the PR **does** seem to introduce text changes into master...)?  And the description implies this will be merged into master at some point.

Sorry, can you walk me through this in a little more detail?

**Comment by tomprince** [comment]
> Is it just as a placeholder to satisfy the documented release process?

Yes. Perhaps that isn't appropriate for documentation-only release.

> Or a helper to get buildbot to do the right thing <...>?

Buildbot doesn't care about PRs, just branches. In particular, you can see the commit status for 
```
Adam Dangoor 	Merge pull request #1092 from ClusterHQ/release-maintenance/flocker-0… … 	
2c44aa7
```
Only has failures on the omnibus builders, and dev-box builder (for broken https SNI links).

The goal is to get https://github.com/ClusterHQ/flocker/commit/2c44aa71b530493e00546f0edb9a2a1edcb55924 tagged as `0.3.2+doc1` and merged into master (the later is no-op). And then, based on that tag, get the documentation deployed.

The documented release procedure isn't correct, it seems.
- There are no unreviewed changes in this release, unlike a full release, which at least updates the release notes.
- In this case (although hopefully not typically), there is in-flight change to the release branch that should not be in the release.

The second thing can perhaps be addressed by having a different branch for documentation releases. But that seems like it might be confusing.

**Pull request closed without merging**
