### PR TITLE
[FLOC-1436] Release 0.3.3dev7

### PR DESCRIPTION
**Pull request by dwgebler**
Fixes FLOC-1436
Updated NEWS
What's New `/docs/advanced/whatsnew.rst` seems to be up-to-date for this dev release, in that as a dev release, the features for What's New are still listed under the Next Release heading. As far as I can tell from the release process docs, this is correct.

### CODE REVIEW

**Comment by dwgebler** [comment]
Please do not merge until release process is completed.

**Comment by adamtheturtle** [comment]
The AWS redirects work.
The NEWS / What's New are reasonable.
I acknowledge that the Quick Start guide will not be updated for this release.

However, as you know, there is a problem with the docs styling (they are unstyled on the staging site).
Therefore please re-submit when this is resolved.

**Comment by adamtheturtle** [comment]
The docs issue seems to have been tracked down, please continue.

**Comment by adamtheturtle** [comment]
Closing because this is not going to be finished.

**Pull request closed without merging**
