### PR TITLE
[FLOC-4113] Expand functional test set up docs

### PR DESCRIPTION
**Pull request by dwgebler**
Fixes FLOC-4113. Explains that cloud backend tests must be run from an instance of the cloud provider and how to set up an instance to run the functional tests.

### CODE REVIEW

**Comment by james-w** [comment]
Hi,

Thanks for fixing this, it would have helped me a lot.

My only comments are that the instructions for getting the dev
env don't quite match everywhere else:

  1. tox does pip install -r requirements.txt before .[dev]. It might well be implicit though?

  2. We have --process-dependency-links everywhere else. It's not needed today because we dropped the testtools fork, but I think we should remain consistent, and either include it here, or remove it from everywhere else.

Also, having a command of some sort that wrapped these steps would be useful, to reduce some of this duplication.

Thanks,

James

**Comment by james-w** [comment]
Oh, merge when you are happy.

**Comment by dwgebler** [comment]
> tox does pip install -r requirements.txt before .[dev]. It might well be implicit though?

`pip install -e .[dev]` or `pip install --editable .[dev]` is functionally equivalent, our `setup.py` reads the requirements file to build its dependency list.

> We have --process-dependency-links everywhere else. It's not needed today because we dropped the testtools fork, but I think we should remain consistent, and either include it here, or remove it from everywhere else.

I've now removed other docs references to `process-dependency-links` in this branch. It's deprecated and gives a warning and seeing as we no longer need it, seems to make more sense to take it out everywhere.

**Comment by james-w** [comment]
--process-dependency-links is still used in every script that installs flocker though.

**Comment by dwgebler** [comment]
> --process-dependency-links is still used in every script that installs flocker though

Also removed from scripts now.

**Pull request merged**
