### PR TITLE
[FLOC-4450] Cancel ping timeout action when AMP connection is lost

### PR DESCRIPTION
**Pull request by wallrj**
Fixes: https://clusterhq.atlassian.net/browse/FLOC-4450

Stacked on #2833 (review that one first)

I refactored the tests a little. It seemed cleaner to have all the connection ping tests together.

I'll trigger the acceptance tests and hopefully we won't see any...

```
AttributeError: 'NoneType' object has no attribute 'abortConnection' after agent disconnects from control service
```

....messages in the remote_logs.log

### CODE REVIEW

**Comment by wallrj** [comment]
I've run the acceptance tests a few times on each platform and there are significantly fewer `abortConnection` errors in this branch

```
[root@ip-172-31-0-243 ~]# find /data/jenkins-jobs/ClusterHQ-flocker/jobs/google-compute-engine-FLOC-4447/ -type f -name 'remote_logs.log' | xargs grep --count "abortConnection"
/data/jenkins-jobs/ClusterHQ-flocker/jobs/google-compute-engine-FLOC-4447/jobs/run_acceptance_loopback_on_AWS_CentOS_7_for_flocker.acceptance/builds/1/archive/remote_logs.log:9
/data/jenkins-jobs/ClusterHQ-flocker/jobs/google-compute-engine-FLOC-4447/jobs/_run_acceptance_on_AWS_Ubuntu_Trusty_with_EBS/builds/1/archive/remote_logs.log:56
/data/jenkins-jobs/ClusterHQ-flocker/jobs/google-compute-engine-FLOC-4447/jobs/_run_acceptance_on_Rackspace_CentOS_7_with_Cinder/builds/1/archive/remote_logs.log:50
/data/jenkins-jobs/ClusterHQ-flocker/jobs/google-compute-engine-FLOC-4447/jobs/run_acceptance_loopback_on_AWS_Ubuntu_Trusty_for_flocker.acceptance/builds/1/archive/remote_logs.log:7
/data/jenkins-jobs/ClusterHQ-flocker/jobs/google-compute-engine-FLOC-4447/jobs/__main_multijob/workspace/run_acceptance_loopback_on_AWS_CentOS_7_for_flocker.acceptance/remote_logs.log:9
/data/jenkins-jobs/ClusterHQ-flocker/jobs/google-compute-engine-FLOC-4447/jobs/__main_multijob/workspace/run_acceptance_loopback_on_AWS_Ubuntu_Trusty_for_flocker.acceptance/remote_logs.log:7
/data/jenkins-jobs/ClusterHQ-flocker/jobs/google-compute-engine-FLOC-4447/jobs/_run_acceptance_on_AWS_CentOS_7_with_EBS/builds/1/archive/remote_logs.log:42
/data/jenkins-jobs/ClusterHQ-flocker/jobs/google-compute-engine-FLOC-4447/jobs/_run_acceptance_on_GCE_CentOS_7_with_GCE/builds/1/archive/remote_logs.log:23
/data/jenkins-jobs/ClusterHQ-flocker/jobs/google-compute-engine-FLOC-4447/jobs/_run_acceptance_on_Rackspace_Ubuntu_Trusty_with_Cinder/builds/1/archive/remote_logs.log:58
/data/jenkins-jobs/ClusterHQ-flocker/jobs/google-compute-engine-FLOC-4447/jobs/_run_acceptance_on_GCE_Ubuntu_Trusty_with_GCE/builds/1/archive/remote_logs.log:34
/data/jenkins-jobs/ClusterHQ-flocker/jobs/google-compute-engine-FLOC-4447/jobs/_run_acceptance_on_GCE_Ubuntu_Trusty_with_GCE/builds/2/archive/remote_logs.log:36
```

```
[root@ip-172-31-0-243 ~]# find /data/jenkins-jobs/ClusterHQ-flocker/jobs/bundle-eliot-tree-FLOC-4451/ -type f -name 'remote_logs.log' | xargs grep --count "abortConnection"
/data/jenkins-jobs/ClusterHQ-flocker/jobs/bundle-eliot-tree-FLOC-4451/jobs/run_acceptance_loopback_on_AWS_CentOS_7_for_flocker.acceptance/builds/1/archive/remote_logs.log:9
/data/jenkins-jobs/ClusterHQ-flocker/jobs/bundle-eliot-tree-FLOC-4451/jobs/_run_acceptance_on_AWS_Ubuntu_Trusty_with_EBS/builds/1/archive/remote_logs.log:57
/data/jenkins-jobs/ClusterHQ-flocker/jobs/bundle-eliot-tree-FLOC-4451/jobs/_run_acceptance_on_Rackspace_CentOS_7_with_Cinder/builds/1/archive/remote_logs.log:46
/data/jenkins-jobs/ClusterHQ-flocker/jobs/bundle-eliot-tree-FLOC-4451/jobs/run_acceptance_loopback_on_AWS_Ubuntu_Trusty_for_flocker.acceptance/builds/1/archive/remote_logs.log:9
/data/jenkins-jobs/ClusterHQ-flocker/jobs/bundle-eliot-tree-FLOC-4451/jobs/__main_multijob/workspace/run_acceptance_loopback_on_AWS_CentOS_7_for_flocker.acceptance/remote_logs.log:9
/data/jenkins-jobs/ClusterHQ-flocker/jobs/bundle-eliot-tree-FLOC-4451/jobs/__main_multijob/workspace/run_acceptance_loopback_on_AWS_Ubuntu_Trusty_for_flocker.acceptance/remote_logs.log:9
/data/jenkins-jobs/ClusterHQ-flocker/jobs/bundle-eliot-tree-FLOC-4451/jobs/_run_acceptance_on_AWS_CentOS_7_with_EBS/builds/1/archive/remote_logs.log:50
/data/jenkins-jobs/ClusterHQ-flocker/jobs/bundle-eliot-tree-FLOC-4451/jobs/_run_acceptance_on_GCE_CentOS_7_with_GCE/builds/1/archive/remote_logs.log:23
/data/jenkins-jobs/ClusterHQ-flocker/jobs/bundle-eliot-tree-FLOC-4451/jobs/_run_acceptance_on_Rackspace_Ubuntu_Trusty_with_Cinder/builds/1/archive/remote_logs.log:39
/data/jenkins-jobs/ClusterHQ-flocker/jobs/bundle-eliot-tree-FLOC-4451/jobs/_run_acceptance_on_GCE_Ubuntu_Trusty_with_GCE/builds/1/archive/remote_logs.log:35
```


```
[root@ip-172-31-0-243 ~]# find /data/jenkins-jobs/ClusterHQ-flocker/jobs/cancel-timer-FLOC-4450 -type f -name 'remote_logs.log' | xargs grep --count "abortConnection"
/data/jenkins-jobs/ClusterHQ-flocker/jobs/cancel-timer-FLOC-4450/jobs/run_acceptance_loopback_on_AWS_CentOS_7_for_flocker.acceptance/builds/1/archive/remote_logs.log:0
/data/jenkins-jobs/ClusterHQ-flocker/jobs/cancel-timer-FLOC-4450/jobs/_run_acceptance_on_AWS_Ubuntu_Trusty_with_EBS/builds/1/archive/remote_logs.log:4
/data/jenkins-jobs/ClusterHQ-flocker/jobs/cancel-timer-FLOC-4450/jobs/_run_acceptance_on_AWS_Ubuntu_Trusty_with_EBS/builds/2/archive/remote_logs.log:6
/data/jenkins-jobs/ClusterHQ-flocker/jobs/cancel-timer-FLOC-4450/jobs/_run_acceptance_on_Rackspace_CentOS_7_with_Cinder/builds/1/archive/remote_logs.log:0
/data/jenkins-jobs/ClusterHQ-flocker/jobs/cancel-timer-FLOC-4450/jobs/run_acceptance_loopback_on_AWS_Ubuntu_Trusty_for_flocker.acceptance/builds/1/archive/remote_logs.log:0
/data/jenkins-jobs/ClusterHQ-flocker/jobs/cancel-timer-FLOC-4450/jobs/__main_multijob/workspace/run_acceptance_loopback_on_AWS_CentOS_7_for_flocker.acceptance/remote_logs.log:0
/data/jenkins-jobs/ClusterHQ-flocker/jobs/cancel-timer-FLOC-4450/jobs/__main_multijob/workspace/run_acceptance_loopback_on_AWS_Ubuntu_Trusty_for_flocker.acceptance/remote_logs.log:0
/data/jenkins-jobs/ClusterHQ-flocker/jobs/cancel-timer-FLOC-4450/jobs/_run_acceptance_on_AWS_CentOS_7_with_EBS/builds/1/archive/remote_logs.log:0
/data/jenkins-jobs/ClusterHQ-flocker/jobs/cancel-timer-FLOC-4450/jobs/_run_acceptance_on_GCE_CentOS_7_with_GCE/builds/1/archive/remote_logs.log:0
/data/jenkins-jobs/ClusterHQ-flocker/jobs/cancel-timer-FLOC-4450/jobs/_run_acceptance_on_GCE_CentOS_7_with_GCE/builds/2/archive/remote_logs.log:0
/data/jenkins-jobs/ClusterHQ-flocker/jobs/cancel-timer-FLOC-4450/jobs/_run_acceptance_on_Rackspace_Ubuntu_Trusty_with_Cinder/builds/1/archive/remote_logs.log:3
/data/jenkins-jobs/ClusterHQ-flocker/jobs/cancel-timer-FLOC-4450/jobs/_run_acceptance_on_Rackspace_Ubuntu_Trusty_with_Cinder/builds/2/archive/remote_logs.log:6
/data/jenkins-jobs/ClusterHQ-flocker/jobs/cancel-timer-FLOC-4450/jobs/_run_acceptance_on_GCE_Ubuntu_Trusty_with_GCE/builds/1/archive/remote_logs.log:0
/data/jenkins-jobs/ClusterHQ-flocker/jobs/cancel-timer-FLOC-4450/jobs/_run_acceptance_on_GCE_Ubuntu_Trusty_with_GCE/builds/2/archive/remote_logs.log:0
```

There are still a up to 6 such errors, but only on ubuntu Trusty on AWS and Rackspace.
As opposed to ~50 on every platform in the other branches.

**Comment by myechuri** [comment]
Thanks for making this change, @wallrj . Two questions:

1) run_acceptance_on_Rackspace_CentOS_7_with_Cinder failure: below error seems unrelated. Can you please confirm?
```
ERROR: Step ‘Publish JUnit test result report’ failed: No test report files were found. Configuration error?
```

2) Can you please explain why we still see abortConnection errors reported below, although we see fewer?
```
There are still a up to 6 such errors, but only on ubuntu Trusty on AWS and Rackspace.
As opposed to ~50 on every platform in the other branches.
```

Thanks!

**Comment by wallrj** [comment]
Thanks @myechuri 

Yeah I think I can explain the remaining errors and discrepancies:

1) The lingering `abortConnection` errors occur during the upgrade test. 
    * `test_upgrade` downgrades to the last marketing release of Flocker and then performs an upgrade to the version built from the branch-under-test The abortConnection errors occur while that old version is briefly running.
    * And that test is skipped on GCE, which explains why we don't see the errors there:
      https://github.com/ClusterHQ/flocker/blob/master/flocker/acceptance/endtoend/test_dataset.py#L96
    * And why do we only see the lingering errors on Ubuntu OS? I think that's because on Centos, the `ssh <remote_host> journalctl --follow` process takes longer to reconnect after the SSH connection dies, and misses the logs during brief period while the old version is running. You can see this from the following snippet from `/data/jenkins-jobs/ClusterHQ-flocker/jobs/cancel-timer-FLOC-4450/jobs/_run_acceptance_on_Rackspace_CentOS_7_with_Cinder/builds/4/archive/remote_logs.log`

```
Not JSON: test-buildbot-kh2rtvyldhuy2-0.localdomain", "action_type": "flocker:agent:converge", "task_level": [2, 7]}

Not an Eliot message: {"_PROCESS_NAME": "<no unit>", "message": "Stopping Flocker Dataset Agent...", "_HOSTNAME": "acceptance-test-buildbot-kh2rtvyldhuy2-1.localdomain"}

18c40e82-1289-4a47-9ce7-eeec0a77b752 -> /1
2016-06-24 10:05:48.688901Z
  message_type: 'twisted:log'
  _HOSTNAME: 'acceptance-test-buildbot-kh2rtvyldhuy2-0.localdomain'
  _PROCESS_NAME: 'flocker-control.service'
  error: False
  message: "ControlAMP connection lost (HOST:IPv4Address(TCP, '23.253.111.251', 4524) PEER:IPv4Address(TCP, '172.99.116.221', 57072))"

ffc2597c-63cf-47e1-a488-3c77f6118300 -> /1
2016-06-24 10:05:53.192863Z
  action_type: 'fsm:transition'
  action_status: 'started'
  _HOSTNAME: 'acceptance-test-buildbot-kh2rtvyldhuy2-0.localdomain'
  _PROCESS_NAME: 'flocker-container-agent.service'
  fsm_identifier: '<flocker.node._loop.ConvergenceLoop object at 0x3f96710>'
  fsm_input: '<ConvergenceLoopInputs=WAKEUP>'
  fsm_rich_input: None
  fsm_state: '<ConvergenceLoopStates=SLEEPING>'
```
You see the last message at `10:05:48`  and the next message at `10:05:53`

And I think the SSH connection dies at this point because while uninstalling Flocker and re-installing Flocker we reconfigure the firewall and briefly block the connection....although that is a bit odd....because usually the iptables connection tracking will allow established connections.

**Comment by myechuri** [comment]
Thanks a lot for explaining, @wallrj ! Please go ahead with the merge.

**Pull request merged**
