### PR TITLE
[FLOC-1771] Split dataset creation

### PR DESCRIPTION
**Pull request by tomprince**
https://clusterhq.atlassian.net/browse/FLOC-1771

This builds on #2157.

[Review on Reviewable](https://reviewable.io/reviews/clusterhq/flocker/2176)

### CODE REVIEW

**Comment by tomprince** [comment]
This looks good. Go ahead and merge once buildbot is happy. Merging this should also mark #2157 as merged.


---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/clusterhq/flocker/2176)

**Comment by tomprince** [comment]
Throwing this back in the backlog as `test_dataset_creation` seems to be failing often.

**Comment by itamarst** [comment]
Given we create datasets in lots of other tests, and that the failing acceptance tests in last run are the first tests that run, I assume it's due to the 120 sleep on container agent startup.

**Comment by tomprince** [comment]
Should we put a 120s sleep somewhere into our test-runner, so we don't trip over this all the time?

**Comment by itamarst** [comment]
I'm ripping out the 120 second sleep as soon as buildbot is happy, PR was just approved.

**Comment by itamarst** [comment]
Specifically see #2177 for removal of 120 second sleep.

**Comment by tomprince** [comment]
#2177 has landed, so I've forced new builds here.

**Pull request merged**
