### PR TITLE
[FLOC-2257] Retry OpenStack calls failing due to OverLimit.

### PR DESCRIPTION
**Pull request by myechuri**

### CODE REVIEW

**Comment by wallrj** [comment]
@myechuri 

Some things that I don't understand / worry about this:

 * The error is called `RequestEntityTooLarge`. 

We import it as `KeystoneOverLimit` and it *can* mean that we've made too many API requests, sure, but mightn't is also mean that we're trying to create a cinder volume that's too large or that we're trying to attach too many cinder volumes to an instance. And in those other circumstances it doesn't make any sense to retry the request. It'd be better to log the entire error and bypass the retry attempts. 

The code looks like this:
 * keystoneclient/openstack/common/apiclient/exceptions.py
```
class RequestEntityTooLarge(HTTPClientError):
    """HTTP 413 - Request Entity Too Large.

    The request is larger than the server is willing or able to process.
    """
    http_status = 413
    message = _("Request Entity Too Large")

    def __init__(self, *args, **kwargs):
        try:
            self.retry_after = int(kwargs.pop('retry_after'))
        except (KeyError, ValueError):
            self.retry_after = 0

        super(RequestEntityTooLarge, self).__init__(*args, **kwargs)

```

So I'd like to understand the circumstances where the `retry_after` keyword is used.


 * Why retry exponentially?

If raised `RequestEntityTooLarge` does have a `retry_after != 0 ` we should just retry after that period of time, right? 

 * What is a typical ``retry_after`` value?

I seem to remember @exarkun saying that on Rackspace it's typically +24h before the API becomes available again.
In which case retrying or waiting in the IBlockDeviceAPI seems wrong. Why not just let the agent keep looping and failing until the API requests eventually start working again?

* And in that case, I think the most valuable part of this branch is the logging of the full `RequestEntityTooLarge` exception.

It currently gets logged as a `twisted:error` (or something) but the repr is truncated so we don't see all the interesting details. And I think this branch also catches the exception without logging the message or the retry_after value in the exception .

Anyway, sorry to weigh in. But I'd like someone to explain how retrying in the IBlockDeviceAPI is expected to help in the real world.

**Comment by wallrj** [comment]
Some links:

* Cloud Servers 1.9. Limits: http://docs.rackspace.com/servers/api/v2/cs-devguide/content/Limits-d1e846.html
 
 * 1.9.3. Get Limits Programmatically: http://docs.rackspace.com/servers/api/v2/cs-devguide/content/ProgrammaticLimits.html

* Rackspace Cloud Glossary: http://www.rackspace.com/knowledge_center/article/rackspace-cloud-glossary#limits

**Comment by wallrj** [comment]
```
(nova)[~/.../python2.7/site-packages]$ for region in IAD DFW HKG; do echo "REGION: $region";  nova --insecure --os-region "$region" limits 2>/dev/null; done
REGION: IAD
+--------+---------------------------------------+-------+--------+--------+--------------------------+
| Verb   | URI                                   | Value | Remain | Unit   | Next_Available           |
+--------+---------------------------------------+-------+--------+--------+--------------------------+
| POST   | *                                     | 150   | 150    | MINUTE | 2015-06-13T21:23:28.675Z |
| DELETE | /servers/{id}/os-virtual-interfacesv2 | 4     | 4      | MINUTE | 2015-06-13T21:23:28.674Z |
| POST   | /servers                              | 2500  | 2500   | DAY    | 2015-06-13T21:23:28.674Z |
| POST   | /servers/{id}/rax-si-image-schedule   | 10    | 10     | SECOND | 2015-06-13T21:23:28.674Z |
| GET    | *                                     | 1500  | 1499   | MINUTE | 2015-06-13T21:24:28.567Z |
| POST   | /servers/{id}/os-virtual-interfacesv2 | 4     | 4      | MINUTE | 2015-06-13T21:23:28.674Z |
| GET    | /servers/{id}/os-virtual-interfacesv2 | 25    | 25     | MINUTE | 2015-06-13T21:23:28.674Z |
| GET    | /servers/{id}/rax-si-image-schedule   | 10    | 10     | SECOND | 2015-06-13T21:23:28.674Z |
| POST   | /os-networksv2                        | 100   | 100    | DAY    | 2015-06-13T21:23:28.674Z |
| DELETE | /servers/{id}/rax-si-image-schedule   | 10    | 10     | SECOND | 2015-06-13T21:23:28.674Z |
+--------+---------------------------------------+-------+--------+--------+--------------------------+
REGION: DFW
+--------+---------------------------------------+-------+--------+--------+--------------------------+
| Verb   | URI                                   | Value | Remain | Unit   | Next_Available           |
+--------+---------------------------------------+-------+--------+--------+--------------------------+
| POST   | *                                     | 150   | 150    | MINUTE | 2015-06-13T21:24:30.773Z |
| DELETE | /servers/{id}/os-virtual-interfacesv2 | 4     | 4      | MINUTE | 2015-06-13T21:23:30.773Z |
| POST   | /servers                              | 2500  | -3446  | DAY    | 2015-06-14T14:47:33.039Z |
| POST   | /servers/{id}/rax-si-image-schedule   | 10    | 10     | SECOND | 2015-06-13T21:23:30.773Z |
| GET    | *                                     | 1500  | 1499   | MINUTE | 2015-06-13T21:24:30.655Z |
| POST   | /servers/{id}/os-virtual-interfacesv2 | 4     | 4      | MINUTE | 2015-06-13T21:23:30.773Z |
| GET    | /servers/{id}/os-virtual-interfacesv2 | 25    | 25     | MINUTE | 2015-06-13T21:23:30.773Z |
| GET    | /servers/{id}/rax-si-image-schedule   | 10    | 10     | SECOND | 2015-06-13T21:23:30.773Z |
| POST   | /os-networksv2                        | 100   | 100    | DAY    | 2015-06-13T21:23:30.773Z |
| DELETE | /servers/{id}/rax-si-image-schedule   | 10    | 10     | SECOND | 2015-06-13T21:23:30.773Z |
+--------+---------------------------------------+-------+--------+--------+--------------------------+
REGION: HKG
+--------+---------------------------------------+-------+--------+--------+--------------------------+
| Verb   | URI                                   | Value | Remain | Unit   | Next_Available           |
+--------+---------------------------------------+-------+--------+--------+--------------------------+
| POST   | *                                     | 150   | 150    | MINUTE | 2015-06-13T21:23:34.102Z |
| DELETE | /servers/{id}/os-virtual-interfacesv2 | 4     | 4      | MINUTE | 2015-06-13T21:23:34.101Z |
| POST   | /servers                              | 2500  | 2500   | DAY    | 2015-06-13T21:23:34.102Z |
| POST   | /servers/{id}/rax-si-image-schedule   | 10    | 10     | SECOND | 2015-06-13T21:23:34.102Z |
| GET    | *                                     | 1500  | 1499   | MINUTE | 2015-06-13T21:24:33.994Z |
| POST   | /servers/{id}/os-virtual-interfacesv2 | 4     | 4      | MINUTE | 2015-06-13T21:23:34.101Z |
| GET    | /servers/{id}/os-virtual-interfacesv2 | 25    | 25     | MINUTE | 2015-06-13T21:23:34.101Z |
| GET    | /servers/{id}/rax-si-image-schedule   | 10    | 10     | SECOND | 2015-06-13T21:23:34.101Z |
| POST   | /os-networksv2                        | 100   | 100    | DAY    | 2015-06-13T21:23:34.102Z |
| DELETE | /servers/{id}/rax-si-image-schedule   | 10    | 10     | SECOND | 2015-06-13T21:23:34.102Z |
+--------+---------------------------------------+-------+--------+--------+--------------------------+

```

**Comment by wallrj** [comment]
```
(nova)[~/.../python2.7/site-packages]$ for region in IAD DFW HKG; do echo "REGION: $region"; cinder --os-region="$region"  absolute-limits 2>/dev/null; done
REGION: IAD
+-------------------------+-------+
|           Name          | Value |
+-------------------------+-------+
|    maxTotalSnapshots    |   -1  |
| maxTotalVolumeGigabytes |   -1  |
|     maxTotalVolumes     |   -1  |
+-------------------------+-------+
REGION: DFW
+-------------------------+-------+
|           Name          | Value |
+-------------------------+-------+
|    maxTotalSnapshots    |   -1  |
| maxTotalVolumeGigabytes |   -1  |
|     maxTotalVolumes     |   -1  |
+-------------------------+-------+
REGION: HKG
+-------------------------+-------+
|           Name          | Value |
+-------------------------+-------+
|    maxTotalSnapshots    |   -1  |
| maxTotalVolumeGigabytes |   -1  |
|     maxTotalVolumes     |   -1  |
+-------------------------+-------+
(nova)[~/.../python2.7/site-packages]$ for region in IAD DFW HKG; do echo "REGION: $region"; cinder --os-region="$region"  rate-limits 2>/dev/null; done
REGION: IAD
+------+-----+-------+--------+------+----------------+
| Verb | URI | Value | Remain | Unit | Next_Available |
+------+-----+-------+--------+------+----------------+
+------+-----+-------+--------+------+----------------+
REGION: DFW
+------+-----+-------+--------+------+----------------+
| Verb | URI | Value | Remain | Unit | Next_Available |
+------+-----+-------+--------+------+----------------+
+------+-----+-------+--------+------+----------------+
REGION: HKG
+------+-----+-------+--------+------+----------------+
| Verb | URI | Value | Remain | Unit | Next_Available |
+------+-----+-------+--------+------+----------------+
+------+-----+-------+--------+------+----------------+

```

**Comment by wallrj** [comment]
```
(nova)[~/.../python2.7/site-packages]$ for region in IAD DFW HKG; do echo "REGION: $region"; cinder --os-region="$region"  quota-usage 929000 2>/dev/null; done
REGION: IAD
+----------------+--------+----------+-------+
|      Type      | In_use | Reserved | Limit |
+----------------+--------+----------+-------+
|   gigabytes    |  2400  |    0     |   -1  |
| gigabytes_SATA |  2400  |    0     | 10240 |
| gigabytes_SSD  |   0    |    0     | 10240 |
|   snapshots    |   0    |    0     |   -1  |
| snapshots_SATA |   0    |    0     |   -1  |
| snapshots_SSD  |   0    |    0     |   -1  |
|    volumes     |   24   |    0     |   -1  |
|  volumes_SATA  |   24   |    0     |   -1  |
|  volumes_SSD   |   0    |    0     |   -1  |
+----------------+--------+----------+-------+
REGION: DFW
+----------------+--------+----------+-------+
|      Type      | In_use | Reserved | Limit |
+----------------+--------+----------+-------+
|   gigabytes    | 10200  |    0     |   -1  |
| gigabytes_SATA | 10200  |    0     | 10240 |
| gigabytes_SSD  |   0    |    0     | 10240 |
|   snapshots    |   0    |    0     |   -1  |
| snapshots_SATA |   0    |    0     |   -1  |
| snapshots_SSD  |   0    |    0     |   -1  |
|    volumes     |  102   |    0     |   -1  |
|  volumes_SATA  |  102   |    0     |   -1  |
|  volumes_SSD   |   0    |    0     |   -1  |
+----------------+--------+----------+-------+
REGION: HKG
+----------------+--------+----------+-------+
|      Type      | In_use | Reserved | Limit |
+----------------+--------+----------+-------+
|   gigabytes    |  1000  |    0     |   -1  |
| gigabytes_SATA |  1000  |    0     | 10240 |
| gigabytes_SSD  |   0    |    0     | 10240 |
|   snapshots    |   0    |    0     |   -1  |
| snapshots_SATA |   0    |    0     |   -1  |
| snapshots_SSD  |   0    |    0     |   -1  |
|    volumes     |   10   |    0     |   -1  |
|  volumes_SATA  |   10   |    0     |   -1  |
|  volumes_SSD   |   0    |    0     |   -1  |
+----------------+--------+----------+-------+
```

**Comment by wallrj** [comment]
So it looks to me like we are reaching our SATA volume limit in DFW.

**Comment by itamarst** [comment]
Might want this in master, but it seems not in release branch.

**Pull request closed without merging**
