### PR TITLE
[FLOC-2029] Pin python-keystoneclient

### PR DESCRIPTION
**Pull request by adamtheturtle**
Fixes: https://clusterhq.atlassian.net/browse/FLOC-2029

### CODE REVIEW

**Comment by adamtheturtle** [comment]
@wallrj suggested that the Dockerfile dependencies are unnecessary, but that can be dealt with at a later date - the important thing is to get the tests passing.

**Comment by jongiddy** [comment]
Might be worth adding an issue to review this addition later. Since `python-keystoneclient` is not a direct dependency, we should have some system to determine if/when it is no longer required. (`python-keystoneclient-rackspace` could one day not depend on this package (unlikely in this case, but generally possible) and we would still be dragging it in).

**Comment by wallrj** [comment]
I understand now that the problem only happens when you install `Flocker[dev]`, because of the `requests` version in our `dev_requirements` and I guess that's why @tomprince chose to update that version.

But I  think it's a good idea to add `python-keystoneclient` as an explicit dependency, we do depend on it.
If anything the the python-keystoneclient-rackspace should be an optional dependency. 

This seems to have fixed things on buildbot, but when I install locally I get this error:

```
(2029)(keystoneclient-FLOC-2029 ? =)[~/.../HybridLogic/flocker]$ flocker-deploy 
Traceback (most recent call last):
  File "/home/richard/.virtualenvs/2029/bin/flocker-deploy", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/home/richard/.virtualenvs/2029/lib/python2.7/site-packages/pkg_resources.py", line 2829, in <module>
    working_set = WorkingSet._build_master()
  File "/home/richard/.virtualenvs/2029/lib/python2.7/site-packages/pkg_resources.py", line 449, in _build_master
    ws.require(__requires__)
  File "/home/richard/.virtualenvs/2029/lib/python2.7/site-packages/pkg_resources.py", line 742, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/home/richard/.virtualenvs/2029/lib/python2.7/site-packages/pkg_resources.py", line 603, in resolve
    requirements = list(requirements)[::-1]
  File "/home/richard/.virtualenvs/2029/lib/python2.7/site-packages/pkg_resources.py", line 2678, in parse_requirements
    "version spec")
  File "/home/richard/.virtualenvs/2029/lib/python2.7/site-packages/pkg_resources.py", line 2645, in scan_list
    raise ValueError(msg, line, "at", line[p:])
ValueError: ('Expected version spec in', 'Flocker===0.4.1dev1-412-g2d188d8', 'at', '===0.4.1dev1-412-g2d188d8')

```

**Comment by wallrj** [comment]
I installed using `(2029)(keystoneclient-FLOC-2029 ? =)[~/.../HybridLogic/flocker]$ pip install --editable .[dev,doc,release]`

Which has installed these package versions:

```
(2029)(keystoneclient-FLOC-2029 ? =)[~/.../HybridLogic/flocker]$ pip freeze
You are using pip version 6.0.8, however version 7.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
apache-libcloud==0.16.0
awscli==1.7.25
Babel==1.3
backports.ssl-match-hostname==3.4.0.2
bcdoc==0.14.0
bitmath==1.2.3.post4
boto==2.38.0
botocore==0.106.0
cffi==1.0.3
characteristic==14.3.0
colorama==0.3.3
cryptography==0.9
docker-py==0.7.1
docutils==0.12
ecdsa==0.13
effect==0.1a13
eliot==0.7.1
enum34==1.0.4
Fabric==1.10.0
flake8==2.2.0
-e git+git@github.com:ClusterHQ/flocker.git@2d188d82115835b00f5298b2be12a437cabcc444#egg=Flocker-keystoneclient-FLOC-2029
gitdb==0.6.4
GitPython==1.0.0
idna==2.0
ipaddr==2.1.11
ipaddress==1.0.7
iso8601==0.1.10
Jinja2==2.7.3
jmespath==0.7.1
jsonschema==2.4.0
klein==0.2.3
machinist==0.2.0
MarkupSafe==0.23
mccabe==0.2.1
msgpack-python==0.4.6
netaddr==0.7.14
netifaces==0.10.4
nomenclature==0.1.1
oslo.config==1.11.0
oslo.i18n==1.6.0
oslo.serialization==1.5.0
oslo.utils==1.5.0
paramiko==1.15.2
pbr==0.11.0
pep8==1.5.7
pg8000==1.10.1
prettytable==0.7.2
psutil==2.1.2
py==1.4.28
pyasn1==0.1.7
pyasn1-modules==0.0.5
pycparser==2.13
pycrypto==2.6.1
pyenchant==1.6.6
pyflakes==0.8.1
Pygments==2.0.2
pymongo==3.0.2
PyMySQL==0.6.2
pyOpenSSL==0.15.1
pyrsistent==0.9.2
python-cinderclient==1.1.1
python-dateutil==2.4.2
python-keystoneclient==1.4.0
python-keystoneclient-rackspace==0.1.3
python-novaclient==2.24.1
pytz==2015.4
PyYAML==3.10
requests==2.4.3
requests-file==1.0
rsa==3.1.4
selenium==2.44.0
service-identity==14.0.0
simplejson==3.7.2
six==1.9.0
smmap==0.9.0
Sphinx==1.2.2
sphinx-prompt==0.2.2
sphinx-rtd-theme==0.1.6
sphinxcontrib-httpdomain==1.3.0
sphinxcontrib-spelling==2.1.1
stevedore==1.4.0
tl.eggdeps==0.4
tox==1.7.1
treq==0.2.1
Twisted==15.1.0
versioneer==0.10
virtualenv==13.0.1
websocket-client==0.31.0
Werkzeug==0.10.4
wheel==0.24.0
zope.interface==4.1.2

```

**Comment by wallrj** [comment]
Ok. It seems that I have to install `setuptools==3.6` first.


Please merge.

**Pull request merged**
