### PR TITLE
[FLOC 644] Add algolia docsearch to the docs

### PR DESCRIPTION
**Pull request by davidoliverSP2**
Fixes 644

During the researching of why Sphinx markup was appearing in search results, we investigated Algolia docsearch and found it was a simple solution to the problem.

### CODE REVIEW

**Comment by robhaswell** [comment]
Sorry @davidoliverSP2 I have forgotten - how do I see the before-and-after for this fix?

**Comment by msh100** [comment]
This looks really good ❤️  

Does Algolia have any documentation on if this is possible without JS (a results page of some sort)? it may be nice to try and clear that up now. The search will not work without JS at the moment so don't let this hold you up from merging though.

@robhaswell http://clusterhq-staging-docs.s3-website-us-east-1.amazonaws.com/algolia-search-FLOC-644/

**Comment by zubron** [comment]
This works really nicely, thanks @davidoliverSP2! I'm happy for this to be merged unless @robhaswell or @msh100 have any other comments.

**Comment by robhaswell** [comment]
None from me.

**Pull request merged**
