### PR TITLE
[FLOC-1326] Serialise CLI and Node installation in Quickstart.

### PR DESCRIPTION
**Pull request by jongiddy**
Primarily remove `parallel` keywords, and re-indent / re-order correctly.

Made titles imperative. "Install..." rather than "Installing...".

### CODE REVIEW

**Comment by exarkun** [comment]
JIRA issue?

**Comment by exarkun** [comment]
Oops, there it is.

**Comment by itamarst** [comment]
This looks good. Main comment I have is that as discussed elsewhere we probably want this done against `release-0.3.2` branch and then forward-ported.

**Comment by itamarst** [comment]
Also I guess discuss this with Alice before proceeding.

**Pull request closed without merging**
