### PR TITLE
Quickstart cli to client floc 1400

### PR DESCRIPTION
**Pull request by adamtheturtle**
These changes (by @dwgebler) were reviewed as part of FLOC-1399, and should now be merged into master.

### CODE REVIEW

**Comment by wallrj** [comment]
This looks fine and identical to #1155 so I was about to say merge, but then  took a closer look at the build failures and it looks  like this has confused buildbot 

And I wonder if it will confuse buildbot when it lands in master?

The branch build results:
 * http://build.clusterhq.com/boxes-flocker?branch=quickstart-cli-to-client-FLOC-1400

...shows no builds.

And the build results linked from this PR are to the release-maintenance branch. Eg.
 * http://build.clusterhq.com/builders/flocker-lint/builds/3881

Better investigate and understand what's going on before merging I guess.

@tomprince ??

**Comment by adamtheturtle** [comment]
Issue for the above at https://clusterhq.atlassian.net/browse/FLOC-1406.

A new build has been forced at http://build.clusterhq.com/boxes-flocker?branch=quickstart-cli-to-client-FLOC-1400.

**Comment by tomprince** [comment]
If you merge forward, buildbot will build the merge commit, and merge agasint the correct branch.

**Comment by wallrj** [comment]
There's a new build error that I've never seen before:
 * http://build.clusterhq.com/builders/flocker-fedora-20/builds/4102/steps/trial/logs/problems
```
[ERROR]
Traceback (most recent call last):
  File "/srv/buildslave/flocker/venv/lib/python2.7/site-packages/twisted/internet/defer.py", line 140, in maybeDeferred
    result = f(*args, **kw)
  File "/srv/buildslave/flocker/venv/lib/python2.7/site-packages/twisted/trial/_asynctest.py", line 279, in <lambda>
    return lambda: f(*args, **kwargs)
  File "/usr/lib64/python2.7/subprocess.py", line 542, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['zpool', 'destroy', 'testpool_2bf0ff0f-b215-4210-87c5-a8ba7e01d351']' returned non-zero exit status 1

flocker.volume.functional.test_filesystems_zfs.IStoragePoolTests.test_clone_to_creates_new
-------------------------------------------------------------------------------
Ran 1129 tests in 553.888s

FAILED (skips=23, expectedFailures=8, errors=1, successes=1097)
```

...but it can't be related to the changes in this branch.

Looks good to me.

Please merge.

**Pull request merged**
